### ISSUE TITLE
Minikube wazuh-kibana-app API socket hung

### ISSUE THREAD

**Issue by VineelaNarendra** [wazuh/wazuh-kubernetes#100]
with the latest code from local-environment branch I see that the wazuh api socket hung-up issue in the `/usr/share/kibana/optimize/wazuh/logs/wazuhapp-plain.log` PFA how it shows in UI

]
<img width="1000" alt="Screenshot 2020-08-28 at 1 16 54 AM" src="https://user-images.githubusercontent.com/64790765/91488038-57aab880-e8cc-11ea-9a68-6b9efecc02ac.png">

if I do curl from kibana container I get the response fine but with -k option only as the cert is self signed

```
bash-4.2$ curl -k --basic -u foo:bar https://wazuh:55000?pretty
{
   "error": 0,
   "data": {
      "msg": "Welcome to Wazuh HIDS API",
      "api_version": "v3.13.0",
      "hostname": "wazuh-manager-0",
      "timestamp": "Thu Aug 27 2020 19:49:48 GMT+0000 (Coordinated Universal Time)"
   }
}
```
content of the file /usr/share/kibana/optimize/wazuh/config/wazuh.yml looks as below, 
```
hosts:
  - 1513629884013:
      url: https://wazuh
      port: 55000
      user: foo
      password: bar
```

Any idea how to fix this?

**Comment by VineelaNarendra** [comment]
@xr09 can you please add your views here to resolve this.

**Comment by xr09** [comment]
Hi @VineelaNarendra thanks for reporting this, I managed to reproduce it on my local env using kind. We're working on this.

**Comment by xr09** [comment]
Hey @VineelaNarendra I had some issues on my environment related to resources which caused Kibana to fail, I'm pushing these  fixes to a new branch along with a version bump to use `3.13.1` images.

Could you try this branch? https://github.com/wazuh/wazuh-kubernetes/tree/bump-local-env-3.13.1_7.8.0

**Comment by manuasir** [comment]
@VineelaNarendra closing this ticket due to inactivity. Don't hesitate to open a new one if your problem persists after the latest changes.
