### ISSUE TITLE
Missing Logstash folder

### ISSUE THREAD

**Issue by serxansherif** [wazuh/wazuh-kubernetes#102]
According to the Wazhuh Kubernetes installation guide, the Logstash folder should be in the git but I couldn't find it.
Installation guide: https://documentation.wazuh.com/3.13/deploying-with-kubernetes/kubernetes-conf.html
![image](https://user-images.githubusercontent.com/53265420/93016540-aa71b900-f5ca-11ea-8989-2e7022f8b828.png)
**Git**
![image](https://user-images.githubusercontent.com/53265420/93016535-9d54ca00-f5ca-11ea-8071-21ee15e4eb57.png)

**Comment by manuasir** [comment]
Hello @serxansherif 

You're right. I'll address this issue in the wazuh-documentation repo and I'll fix it.
Sorry for the inconvenience.

Regards
