### ISSUE TITLE
Wazuh clusterkey not being replaced in config

### ISSUE THREAD

**Issue by aroes** [wazuh/wazuh-kubernetes#110]
Since the wazuh docker image has not been rebuilt on dockerhub since the secrets change, the cluster key in the configmaps is not being replaced as expected (old version of 00-wazuh.sh).

**Comment by manuasir** [comment]
Hello @aroes ,

I assume you're using the `master` branch, where all the new features and changes are being merged. This branch does not guarantee stability, but you can use our latest stable release which corresponds with the [v3.13.2_7.91](https://github.com/wazuh/wazuh-kubernetes/tree/v3.13.2_7.9.1) tag. Let me know if this helps.

**Comment by aroes** [comment]
Ah sorry I assumed master was stable, thank you. Since I'd like to use the secrets, I'll wait until the next version of wazuh docker.
