### ISSUE TITLE
chroot error on start es pod

### ISSUE THREAD

**Issue by AdamWyzgol** [wazuh/wazuh-kubernetes#112]
I just install wazuh on new kubernetes cluster, on ES I have in logs error:
chroot: cannot change root directory to /: Operation not permitted 
This occures only on this pod, I tried also older versions of image, there was the same problem. Where could be the issue?

**Comment by AdamWyzgol** [comment]
after adding to container definition:
        securityContext:
          runAsUser: 1000
it starts working, the same problem I had after changed image to base elasticsearch image. I foud that resolution after read this https://github.com/elastic/helm-charts/issues/357#issuecomment-553371078 maybe it help someone.

**Comment by xr09** [comment]
Hi @AdamWyzgol, 

I'm trying to emulate this error. Could you share more details about your Kubernetes environment (minikube, EKS, GKE, etc) and the exact steps you followed for the deployment?

**Comment by AdamWyzgol** [comment]
I have some more details, the same error occure on manager pods. I think it could be related with CRI-o based cluster. It is custom installation from kubeadm, latest version of k8s and crio.

**Comment by AdamWyzgol** [comment]
I found this https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/167 it is probalby the issue

**Comment by xr09** [comment]
Thanks for the PR we'll give it a look soon.

**Comment by xr09** [comment]
Fixed by #113
