### ISSUE TITLE
Nodes restarting in different Availability Zones

### ISSUE THREAD

**Issue by gwvandesteeg** [wazuh/wazuh-kubernetes#116]
In the StorageClass definition you're missing an important setting of WaitForFirstConsumer.
This resolves the issue of topology constrained storage backends (such as AWS EBS).
```
volumeBindingMode: WaitForFirstConsumer
```
as per:  https://kubernetes.io/docs/concepts/storage/storage-classes/

The main cause of this would be where the instance using the volume is restarted for some reason onto a different availability zone.  The above mitigates that and constrains the pod to be more accurately restricted to being in the same zone as the storage (AWS prohibits cross zone EBS bindings).

**Comment by xr09** [comment]
Hey @gwvandesteeg, thanks a lot for reaching out, I'll take a look at this and get it fixed.

**Comment by ailoyu** [comment]
Thanks a lot! I fixed it
