### ISSUE TITLE
Agent is never connected 

### ISSUE THREAD

**Issue by Bilvani** [wazuh/wazuh-kubernetes#120]
If I am making use of telnet in order to check connectivity I can see that it is connected but then the agent is never connected on master.

<img width="501" alt="Screenshot 2020-11-18 at 5 31 16 PM" src="https://user-images.githubusercontent.com/71020465/99529292-8e710600-29c5-11eb-8593-07c0e99aed74.png">

<img width="925" alt="Screenshot 2020-11-18 at 5 38 08 PM" src="https://user-images.githubusercontent.com/71020465/99528899-f3782c00-29c4-11eb-8c3a-5575b37c8342.png">

<img width="541" alt="Screenshot 2020-11-18 at 5 40 34 PM" src="https://user-images.githubusercontent.com/71020465/99529090-481ba700-29c5-11eb-8194-9daa158a4d95.png">

**Comment by xr09** [comment]
Hey @Bilvani sorry for the dealy, did you solved this one?

**Comment by Bilvani** [comment]
The issue is resolved
