### ISSUE TITLE
Apply Wazuh tools name changing to the wazuh-kubernetes

### ISSUE THREAD

**Issue by danimegar** [wazuh/wazuh-kubernetes#129]
## Description
Hello team. 

According to the changes proposed at wazuh/wazuh#6766, the following tools will be renamed or totally removed from new Wazuh installations.

- `ossec-control` -> `wazuh-control`
- `ossec-regex` -> `wazuh-regex`
- `rootcheck_control` -> Removed
- `syscheck_control` -> Removed
- `syscheck_update` -> Removed
- `ossec-logtest` -> Removed (it was replaced by `wazuh-logtest`)
- `ossec-makelists` -> Removed

We saw references to these tools in this repo. Please, update these references according to the proposed renaming.

**Comment by xr09** [comment]
Hey there @danimegar!

On this repository we're only referencing `ossec-control` as part of the documentation on the `ossec.conf` used for the managers, not as a direct command. 

However on the `wazuh-docker` repository we're using it as a command more than once. A proper refactor will be required, I replicated this issue there: https://github.com/wazuh/wazuh-docker/issues/418

**Comment by xr09** [comment]
Fixed by #136
