### ISSUE TITLE
Kustomize error: No matches for wazuh-elasticsearch and wazuh-manager-worker

### ISSUE THREAD

**Issue by brunobcestari** [wazuh/wazuh-kubernetes#158]
I was trying to install Wazuh as a local deployment using minikube following the instructions in https://documentation.wazuh.com/current/deploying-with-kubernetes/kubernetes-local-env.html. 
After `$ kubectl apply -k envs/local-env/` I got the following error:

`error: no matches for IdId apps_v1_StatefulSet|~X|wazuh-elasticsearch; failed to find unique target for patch apps_v1_StatefulSet|wazuh-elasticsearch`

The error was fixed after adding `namespace: wazuh` under the `metadata` key in
`envs/local-env/elastic-resources.yaml` and `envs/local-env/wazuh-resources.yaml`

Notes:
The minikube namespace was set as `default`
Not sure if it was an isolated issue due to my local configuration so I didn't open a PR to change those files

**Comment by okynos** [comment]
Closed.
