### ISSUE TITLE
wazuh steps for deploying load balancers for master and worker creates classic ELBs instead of NLB

### ISSUE THREAD

**Issue by rohans175** [wazuh/wazuh-kubernetes#166]
Reviewing the steps and having tried out the configuration at our end, i see the sts files for master and server are configured to create a Classic ELB instead of an NLB. I read somewhere in the wazuh docs that only NLB can be used since the communication happens over tcp protocol. Did i miss a configmap somewhere? Please review and let us know, we are having issues related to master - agent communication.

**Comment by rohans175** [comment]
Closing this issue. Communication needs to be tcp, the load balancers can be classic ELBs.

**Comment by dashashutosh24** [comment]
@rohans175 I am facing a similar issue. Did you get the master and agents communication up and running with a NLB or an ALB ?
