### ISSUE TITLE
Default wazuh dash username/password not documented

### ISSUE THREAD

**Issue by nnachefski** [wazuh/wazuh-kubernetes#169]
If someone was to deploy this stack using the local-env template, what is the default username/password?

**Comment by trigat** [comment]
Default credentials are under https://github.com/wazuh/wazuh-kubernetes/tree/master/wazuh/secrets

For example, admin:SecretPassword

**Comment by alberpilot** [comment]
Let me close this issue. Please don't hesitate to re-open if needed.
