### ISSUE TITLE
Personalize worker name

### ISSUE THREAD

**Issue by St4n** [wazuh/wazuh-kubernetes#190]
Hello,

When deploying the statefullset of workers, each worker has a name in the kubernetes cluster.

In the configmap for configuring the worker, there is a section for configuring cluster where we need to put the node_name :   

node_name to_be_replaced_by_hostname node_name

But we cannot specify a configmap for each worker node, so each worker will have the same node_name in the cluster.

We use helm here and a good solution for that would be to have an environment variable for the pod that would set the worker name.

Is there a such environment variable? for cluster key we have WAZUH_CLUSTER_KEY env var that do the job.

Is there a documentation somewhere about all environment variables availables for wazuh? I didn't find it.

Thanks,
Regards,
Stéphane.

**Comment by teddytpc1** [comment]
Hi @St4n,
The `node_name` is configured dynamically when the container starts. This is done by a `sed` command configured in an init script of the Wazuh Docker image. Please check the following file in the `wazuh-docker` repository.
- https://github.com/wazuh/wazuh-docker/blob/master/wazuh-odfe/config/etc/cont-init.d/0-wazuh-init (line 150)

The is no need to configure a variable as the init script will replace the `to_be_replaced_by_hostname` string for the container `hostname`.

**Comment by St4n** [comment]
Hi @teddytpc1,
Absolutely, I didn't figure that there was an init container modifying required parameters.
You can close the ticket.
