### ISSUE TITLE
 Adapt the Kubernetes deployment to use the new Wazuh indexer default ports.

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-kubernetes#219]
As mentioned in https://github.com/wazuh/wazuh-packages/issues/1285, the Wazuh indexer must use the same default ports as elasticsearch. We need to change all deployment-involved files to 9200 and 9300 as default ports.

**Comment by vcerenu** [comment]
Changed port 9700 to 9200 and 9800 to 9300 in all files carrying this setting.
Deployment test was performed and it worked without errors.
