### ISSUE TITLE
Adapt the Kubernetes deployment to use the new Wazuh dashboard configuration file name.

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-kubernetes#221]
Based on https://github.com/wazuh/wazuh-packages/issues/1282, we need to change the Wazuh dashboard configuration file from dashboard.yml to opensearch_dashboards.yml.

**Comment by teddytpc1** [comment]
The changes were added to PR https://github.com/wazuh/wazuh-kubernetes/pull/217

**Comment by teddytpc1** [comment]
The Indexer username and password were removed from opensearch_dashboards.yml file.
