### ISSUE TITLE
local environment kubernetes add agent error

### ISSUE THREAD

**Issue by king5718** [wazuh/wazuh-kubernetes#224]
I have deployed the wazuh-manager on local environment.
But when I want to add the agent to my manager,I get this error:
```
C:\Program Files (x86)\ossec-agent>.\agent-auth.exe -m 140.122.184.183
2022/03/11 15:24:04 agent-auth: INFO: Started (pid: 22592).
2022/03/11 15:24:04 agent-auth: INFO: Requesting a key from server: 140.122.184.183
2022/03/11 15:24:04 agent-auth: INFO: No authentication password provided
2022/03/11 15:24:04 agent-auth: INFO: Using agent name as: DESKTOP-JNCNE6S
2022/03/11 15:24:04 agent-auth: INFO: Waiting for server reply
2022/03/11 15:24:04 agent-auth: ERROR: Invalid password (from manager)
2022/03/11 15:24:04 agent-auth: ERROR: Unable to add agent (from manager)
```
this is my service of my wazuh-kubernetes
```
➜tim@master:~$ kubectl get svc -n=wazuh
NAME                  TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                          AGE
elasticsearch         LoadBalancer   10.104.96.217    <pending>     9200:32351/TCP                   46h
kibana                LoadBalancer   10.110.186.141   <pending>     443:32755/TCP                    46h
wazuh                 LoadBalancer   10.108.129.164   <pending>     1515:31024/TCP,55000:30320/TCP   46h
wazuh-cluster         ClusterIP      None             <none>        1516/TCP                         46h
wazuh-elasticsearch   ClusterIP      None             <none>        9300/TCP                         46h
wazuh-workers         LoadBalancer   10.102.107.10    <pending>     1514:32136/TCP                   46h

```
how can I get the valid password or no need password to vertify?

**Comment by king5718** [comment]
I found the password in pod wazuh-manager-master-0 `/var/ossec/etc/authd.pass`.
After I use this password .`\agent-auth.exe -m 140.122.184.183 -P password`, I can see it in the agent of kibana.
But I get shis error : The agent has been registered but has not yet connected to the manager.
The log in my agent `ossec.txt` still has the same error:
```
2022/03/11 16:51:50 wazuh-agent: INFO: Requesting a key from server: 140.122.184.183
2022/03/11 16:51:50 wazuh-agent: INFO: No authentication password provided
2022/03/11 16:51:50 wazuh-agent: INFO: Using agent name as: DESKTOP-JNCNE6S
2022/03/11 16:51:50 wazuh-agent: INFO: Waiting for server reply
2022/03/11 16:51:50 wazuh-agent: ERROR: Invalid password (from manager)
2022/03/11 16:51:50 wazuh-agent: ERROR: Unable to add agent (from manager)

```

**Comment by teddytpc1** [comment]
Hi @king5718.
Were are you getting the `140.122.184.183` IP from? I do not see that IP in the `kubectl get svc -n=wazuh` command output.
Take into account that you have two different services (load balancer) to connect to the managers:
- One of them is listening on port 1515 (for agent registration).
- The other one is listening on port 1514 (for agent connection).
So, the registration command should be run against the agent registration balancer and the agent's `ossec.conf` should point to the agent connection balancer. 
Can you tell us more about the architecture of your deployment please?
And also, please share the `ossec.conf` from the agent.

**Comment by king5718** [comment]
我已經解決了這個問題。
在連接到端口 1514 之前，我通過 1515 端口進行了身份驗證
。感謝您的回复。

**Comment by teddytpc1** [comment]
Glad to hear that. You are welcome.
