### ISSUE TITLE
`config.yml` must be adapted to the new format

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-kubernetes#236]
Based on https://github.com/wazuh/wazuh-packages/issues/1413 we need to modify the current repository use of `config.yml` file.

**Comment by fcaffieri** [comment]
For K8s, the changes applied in the config and the wazuh-certs-tool have no effect because the certificates are generated directly with the OpenSSL command, and then the secrets are generated.
wazuh-kubernetes/wazuh/certs/indexer_cluster/generate_certs.sh:
```
...
echo "* Filebeat cert"

echo "create: filebeat-key-temp.pem"

openssl genrsa -out filebeat-key-temp.pem 2048

echo "create: filebeat-key.pem"

openssl pkcs8 -inform PEM -outform PEM -in filebeat-key-temp.pem -topk8 -nocrypt -v1 PBE-SHA1-3DES -out filebeat-key.pem
...
```
and so with the rest of the certificates.
