### ISSUE TITLE
I can't generate certs

### ISSUE THREAD

**Issue by AliceMongodin** [wazuh/wazuh-kubernetes#260]
Hello, i'm trying to set up wazuh, and the first step is to generate certs, but I have some issues : 
here are screens of what the input is : 
in the dashboard_http dir :
<img width="392" alt="image" src="https://user-images.githubusercontent.com/90464649/170224986-68567044-832c-485a-b662-858360131540.png">
 the other one (indexer_cluster works fine). Then if I try to apply this goes :
![image](https://user-images.githubusercontent.com/90464649/170225395-86bd0926-0e31-4325-9ed1-a56b6502539e.png)

If anyone has an idea :) thanks

**Comment by ryangniadek** [comment]
I'm having the same issue on the `stable` branch as of 6/3/22 #270

**Comment by ryangniadek** [comment]
Thanks Raul - this issue is no longer in the critical path for me but for the sake of the thread: LibreSSL 2.8.3 and Darwin Kernel Version 21.4.0 (MacOS Monterey 12.3.1)

**Comment by rauldpm** [comment]
Hello @ryangniadek and @AliceMongodin 

Currently I have been able to reproduce this problem on a Macos Monterrey with kernel 21.2.0 and LibreSSL version 2.8.3

As a note, keep in mind that we do not have Wazuh indexer and Wazuh dashboard packages for ARM architectures yet, so you should use amd64 architecture.

Investigating I have been able to verify that adding `-subj "/C=US/L=California/O=Company/CN=dashboard"` to the creation of wazuh dashboard certificates, the certificates are generated correctly, the command would be as follows:

https://github.com/wazuh/wazuh-kubernetes/blob/95e18d3ab192a43d8b6750753461cc8132825241/wazuh/certs/dashboard_http/generate_certs.sh#L6

- openssl req -x509 -batch -nodes -days 365 -newkey rsa:2048 -keyout key.pem -out cert.pem -subj "/C=US/L=California/O=Company/CN=dashboard"

After this, when executing the script, the following output is obtained, generating a cert.pem file and a key.pem file:

```
% bash generate_certs.sh
Generating a 2048 bit RSA private key
..+++
..............................+++
writing new private key to 'key.pem'
-----
```
