### ISSUE TITLE
Error logs in new deployment related to internal certificates

### ISSUE THREAD

**Issue by andraspavelbaystream** [wazuh/wazuh-kubernetes#280]
Hello,

I am building my new test environment, and I use the generate-certs.sh for the indexer cluster preparation.
The script runs successfully, and the certificates are available.
I can start up the cluster, but, in the Wazuh Indexer pod I get these logs:

`[2022-07-07T18:10:18,097][WARN ][o.o.h.AbstractHttpServerTransport] [wazuh-indexer-0] caught exception while handling client http traffic, closing connection Netty4HttpChannel{localAddress=/10.244.1.37:9200, remoteAddress=/10.244.0.38:54268}
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:477) ~[netty-codec-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:623) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:586) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.72.Final.jar:4.1.72.Final]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
        at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
        at sun.security.ssl.Alert.createSSLException(Alert.java:117) ~[?:?]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:356) ~[?:?]
        at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293) ~[?:?]
        at sun.security.ssl.TransportContext.dispatch(TransportContext.java:202) ~[?:?]
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:171) ~[?:?]
        at sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:736) ~[?:?]
        at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:691) ~[?:?]
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:506) ~[?:?]
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:482) ~[?:?]
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:637) ~[?:?]
        at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:295) ~[netty-handler-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1341) ~[netty-handler-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1234) ~[netty-handler-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1283) ~[netty-handler-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[netty-codec-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) ~[netty-codec-4.1.72.Final.jar:4.1.72.Final]
        ... 16 more`

In the Wazuh Manager and Worker pods I get this error message:

`2022-07-07T18:10:49.988Z        ERROR   [publisher_pipeline_output]     pipeline/output.go:154  Failed to connect to backoff(elasticsearch(https://wazuh-indexer-0.wazuh-indexer:9200)): Get "https://wazuh-indexer-0.wazuh-indexer:9200": x509: certificate signed by unknown authority
2022-07-07T18:10:49.988Z        INFO    [publisher_pipeline_output]     pipeline/output.go:145  Attempting to reconnect to backoff(elasticsearch(https://wazuh-indexer-0.wazuh-indexer:9200)) with 32 reconnect attempt(s)
2022-07-07T18:10:49.989Z        INFO    [publisher]     pipeline/retry.go:219   retryer: send unwait signal to consumer
2022-07-07T18:10:49.989Z        INFO    [publisher]     pipeline/retry.go:223     done`

Is there anything else related to certificate configuration I should do to solve this issue?

Thanks,
Andras

**Comment by andraspavelbaystream** [comment]
Hi @vcerenu 

Do you have perhaps any manual workaround to bypass this issue for now?

Thanks,
Andras

**Comment by andraspavelbaystream** [comment]
Hi @vcerenu 

Thanks for your reply.

I am running our clusters in Oracle Kubernetes Engine.
The only things which were changed are only the storage class provider to use Oracle's provisioner and the secrets.
The storage disks are created and mapped as expected.

Here are the permissions: (777)
![image](https://user-images.githubusercontent.com/39588110/178570617-26fd9d38-f516-4fc1-a067-d7f83eecfb23.png)

For the Dashboard, I used our wildcard cert., putting key.pem and cert.pem to its folder. It loads kibana with the proper certificate on port 443.
For the indexer, I used the "generate_certs.sh" script. Pods are created fine, but I have the logs mentioned above.
Logging in to the pods, I found the proper CA, I checked to be sure it is the one I generated, but, it is in the indexer and wazuh pods.

Any suggestion, or tip?

Thank you so much!

**Comment by vcerenu** [comment]
Hello @andraspavelbaystream 

Within the Wazuh dashboard deployment we use the same root-ca that is used for indexer and manager, so this may be causing problems.

Can you perform the deployment from scratch by generating the certificates with both scripts? And if you made any changes in the opensearch.yml or opensearch-dashboards.yml files I ask you to add it

**Comment by andraspavelbaystream** [comment]
Hi @vcerenu 

Just did a fresh deployment after re-generating all certs.
I see no changes in the logs, the only difference is that kibana uses now that self-signed certificate.
To be honest, I am not sure how it differs from using our public cert, as the Dashboard script does not generate a new certificate using the CA we create with the indexer cluster certificate generation script. (_so, the dashboard cert will be still a foreign cert for the indexer stack_)

I didn't do changes to the opensearch.yml or opensearch-dashboards.yml files.

I attached the cleaned up version of the template I am using.

[wazuh-kubernetes-4.3-stable - PUBLIC.zip](https://github.com/wazuh/wazuh-kubernetes/files/9099036/wazuh-kubernetes-4.3-stable.-.PUBLIC.zip)

**Comment by vcerenu** [comment]
Hi @andraspavelbaystream 

The errors that are in the attached logs are due to problems with the certificates, I do not know how Oracle Cloud is mounting the certificates in the pods but I would like to check if the certificates are where they belong according to the default configuration:

```
$ kubectl exec -it <wazuh-dashboard-pod>-n wazuh -- ls -ltr /usr/share/wazuh-dashboard/config/certs/
$ kubectl exec -it wazuh-manager-master-0 -n wazuh -- ls -ltr /etc/ssl/
$ kubectl exec -it wazuh-indexer-0 -n wazuh -- ls -ltr /usr/share/wazuh-indexer/config/certs/
```

This is the result I have in my deployment on EKS

```
$ kubectl exec -it pod/wazuh-dashboard-79465c7bcd-qkrc7 -n wazuh -- ls -ltr /usr/share/wazuh-dashboard/config/certs/
total 20
-r-------- 1 wazuh-dashboard wazuh-dashboard 1257 Jul  1 15:48 dashboard.pem
-r-------- 1 wazuh-dashboard wazuh-dashboard 1704 Jul  1 15:48 dashboard-key.pem
-rw-r--r-- 1 root            root            1249 Jul 13 09:56 root-ca.pem
-rw-r--r-- 1 root            root            1704 Jul 13 09:56 key.pem
-rw-r--r-- 1 root            root            1245 Jul 13 09:56 cert.pem

$ kubectl exec -it wazuh-manager-master-0 -n wazuh -- ls -ltr /etc/ssl/
total 40
drwx------ 2 root root      6 Jun 15 18:16 private
-rw-r--r-- 1 root root  10909 Jun 15 18:16 openssl.cnf
drwxr-xr-x 2 root root  12288 Jun 29 10:23 certs
-rw-r--r-- 1 root wazuh  1249 Jul 12 20:27 root-ca.pem
-rw-r--r-- 1 root wazuh  1127 Jul 12 20:27 filebeat.pem
-rw-r--r-- 1 root wazuh  1704 Jul 12 20:27 filebeat.key

$ kubectl exec -it wazuh-indexer-0 -n wazuh -- ls -ltr /usr/share/wazuh-indexer/config/certs/
Defaulted container "wazuh-indexer" out of: wazuh-indexer, volume-mount-hack (init), increase-the-vm-max-map-count (init)
total 32
-r-------- 1 wazuh-indexer wazuh-indexer 1704 Jun 29 10:24 root-ca.key
-r-------- 1 wazuh-indexer wazuh-indexer 1253 Jun 29 10:24 indexer.pem
-r-------- 1 wazuh-indexer wazuh-indexer 1704 Jun 29 10:24 indexer-key.pem
-rw-r--r-- 1 root          root          1704 Jul 12 20:27 node-key.pem
-rw-r--r-- 1 root          root          1249 Jul 12 20:27 root-ca.pem
-rw-r--r-- 1 root          root          1139 Jul 12 20:27 node.pem
-rw-r--r-- 1 root          root          1123 Jul 12 20:27 admin.pem
-rw-r--r-- 1 root          root          1704 Jul 12 20:27 admin-key.pem
```

I enclose the documentation for you to verify if you are performing the same deployment that we suggest

https://documentation.wazuh.com/current/deployment-options/deploying-with-kubernetes/kubernetes-deployment.html

**Comment by andraspavelbaystream** [comment]
Hi @vcerenu 

Yes, I can confirm I did those steps what are in the documentation, the difference is I went with the "stable" branch.
Also, kindly note that we have a production cluster on OKE, working fine, this install is for the test environment for upgrading from 4.2 to 4.3.
We have no issue there with certificates.

The certificates are mapped correctly I think, also, cat'ed the root-cas, you can see the content are correct as well. (see below)

Thank you so much!

Andras

```
PS D:\OneDrive - Company Corporation\Wazuh\wazuh-kubernetes-4.3-stable> kubectl exec -it wazuh-dashboard-5778695ccd-fq6r9 -n wazuh -- ls -ltr /usr/share/wazuh-dashboard/config/certs/
total 20
-r--------. 1 wazuh-dashboard wazuh-dashboard 1257 Jun  1 01:20 dashboard.pem
-r--------. 1 wazuh-dashboard wazuh-dashboard 1704 Jun  1 01:20 dashboard-key.pem
-rw-r--r--. 1 root            root            1277 Jul 13 04:36 root-ca.pem
-rw-r--r--. 1 root            root            1704 Jul 13 04:36 key.pem
-rw-r--r--. 1 root            root            1245 Jul 13 04:36 cert.pem
PS D:\OneDrive - Company Corporation\Wazuh\wazuh-kubernetes-4.3-stable> kubectl exec -it wazuh-manager-master-0 -n wazuh -- ls -ltr /etc/ssl/
total 40
drwx------. 2 root root     6 May  3 17:49 private
-rw-r--r--. 1 root root 10909 May  3 17:49 openssl.cnf
drwxr-xr-x. 2 root root 12288 Jun  1 01:15 certs
-rw-r--r--. 1 root root  1159 Jul 13 04:36 filebeat.pem
-rw-r--r--. 1 root root  1277 Jul 13 04:36 root-ca.pem
-rw-r--r--. 1 root root  1704 Jul 13 04:36 filebeat.key
PS D:\OneDrive - Company Corporation\Wazuh\wazuh-kubernetes-4.3-stable> kubectl exec -it wazuh-indexer-0 -n wazuh -- ls -ltr /usr/share/wazuh-indexer/config/certs/
Defaulted container "wazuh-indexer" out of: wazuh-indexer, volume-mount-hack (init), increase-the-vm-max-map-count (init)
total 32
-r--------. 1 wazuh-indexer wazuh-indexer 1704 Jun  1 01:19 root-ca.key
-r--------. 1 wazuh-indexer wazuh-indexer 1253 Jun  1 01:19 indexer.pem
-r--------. 1 wazuh-indexer wazuh-indexer 1704 Jun  1 01:19 indexer-key.pem
-rw-r--r--. 1 root          root          1277 Jul 13 04:36 root-ca.pem
-rw-r--r--. 1 root          root          1168 Jul 13 04:36 node.pem
-rw-r--r--. 1 root          root          1704 Jul 13 04:36 node-key.pem
-rw-r--r--. 1 root          root          1155 Jul 13 04:36 admin.pem
-rw-r--r--. 1 root          root          1700 Jul 13 04:36 admin-key.pem
PS D:\OneDrive - Company Corporation\Wazuh\wazuh-kubernetes-4.3-stable> dir .\wazuh\certs\dashboard_http\

    Directory: D:\OneDrive - Company Corporation\Wazuh\wazuh-kubernetes-4.3-stable\wazuh\certs\dashboard_http

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          2022.07.13     6:31           1245 cert.pem
-a---          2022.07.06    10:33            183 generate_certs.sh
-a---          2022.07.13     6:31           1704 key.pem

PS D:\OneDrive - Company Corporation\Wazuh\wazuh-kubernetes-4.3-stable> dir .\wazuh\certs\indexer_cluster\

    Directory: D:\OneDrive - Company Corporation\Wazuh\wazuh-kubernetes-4.3-stable\wazuh\certs\indexer_cluster

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          2022.07.08    13:36           1700 admin-key-temp.pem
-a---          2022.07.08    13:36           1700 admin-key.pem
-a---          2022.07.08    13:36            972 admin.csr
-a---          2022.07.08    13:36           1155 admin.pem
-a---          2022.07.08    13:36           1704 dashboard-key-temp.pem
-a---          2022.07.08    13:36           1704 dashboard-key.pem
-a---          2022.07.08    13:36            976 dashboard.csr
-a---          2022.07.08    13:36           1159 dashboard.pem
-a---          2022.07.08    13:36           1704 filebeat-key-temp.pem
-a---          2022.07.08    13:36           1704 filebeat-key.pem
-a---          2022.07.08    13:36            976 filebeat.csr
-a---          2022.07.08    13:36           1159 filebeat.pem
-a---          2022.07.08    13:36           2544 generate_certs.sh
-a---          2022.07.08    13:36           1704 node-key-temp.pem
-a---          2022.07.08    13:36           1704 node-key.pem
-a---          2022.07.08    13:36            985 node.csr
-a---          2022.07.08    13:36           1168 node.pem
-a---          2022.07.08    13:36           1704 root-ca-key.pem
-a---          2022.07.08    13:36           1277 root-ca.pem

PS D:\OneDrive - Company Corporation\Wazuh\wazuh-kubernetes-4.3-stable> Get-Content .\wazuh\certs\indexer_cluster\root-ca.pem                                 -----BEGIN CERTIFICATE-----
MIIDgzCCAmugAwIBAgIUFsouxoFwv5WGmclX5WnWzJNkg/AwDQYJKoZIhvcNAQEL
BQAwUTELMAkGA1UEBhMCQ0ExETAPBgNVBAcMCE1vbnRyZWFsMR0wGwYDVQQKDBRC
YXlzdHJlYW1Db3Jwb3JhdGlvbjEQMA4GA1UEAwwHcm9vdC1jYTAeFw0yMjA3MDgx
MTM2NDBaFw0zMjA3MDUxMTM2NDBaMFExCzAJBgNVBAYTAkNBMREwDwYDVQQHDAhN
b250cmVhbDEdMBsGA1UECgwUQmF5c3RyZWFtQ29ycG9yYXRpb24xEDAOBgNVBAMM
B3Jvb3QtY2EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCdKNWyLccR
ibJxnc2PTk0FQKqExJeB/xc9/OFA5HK0rFN5te/ray9F13vuEyg7OPl0uPpdX65i
ZW0r2biz4VqPpMHb5sVgN/zTJv1YWcCWHUAoxZ9hcUKps0hx3+xRFG4uCPb/ifeL
KuN47J4duTsSxC5Snpu1ZXIIp78YfdbF6zGJSfN+wwMxOwtOsxkf6UgpFDn2RYEN
biDoIEAc0QSNVzd91t/Z2oCDBTKEXt1LTgL7M4VxTXGUlb09i0RYyGUVEy9Svpd7
Iev1RzjzIsoOhB/EGVRrFU0LNAhOG4kmctSZPBfnoY9IUToGHWrboyRoZOIEk9iC
NLaHri/y18jnAgMBAAGjUzBRMB0GA1UdDgQWBBRc7VHWMB6u1u6CKemMcxvApPHY
lTAfBgNVHSMEGDAWgBRc7VHWMB6u1u6CKemMcxvApPHYlTAPBgNVHRMBAf8EBTAD
AQH/MA0GCSqGSIb3DQEBCwUAA4IBAQBQjhPeM8G+HzadewSTEmlteUIHlNTgnFWh
IMbRcvud3zt1CUzmNbgfyEuLCYt6AhaJubSJA4XAdHAKJgy6/RyxdqI6uFvfiHZZ
7s8OqPtUvJ5JZQJwp1xkVirtE0uuZEH0z0dMfbcuiCMsOwFQbZVl5Z8xcrjH2gCU
Ki9uwmTobotoHHb5hzMQxOQB8Otvw8b6mcBAjRFsNjZW4qO+1JtzR/YJFoeUZmFE
DQgF+Y77EO9Ygm7ukb69MTZDJ21mgW3cDafziSQzdr/2Q8sO+525PqZuk+rXAdgU
PPHUGDuix+ukuuOjIKlb/e7lylKr1KCQPcrvTRERaYck+kzgNiQA
-----END CERTIFICATE-----
PS D:\OneDrive - Company Corporation\Wazuh\wazuh-kubernetes-4.3-stable> kubectl exec -it wazuh-indexer-0 -n wazuh -- cat /usr/share/wazuh-indexer/config/certs/root-ca.pem 
Defaulted container "wazuh-indexer" out of: wazuh-indexer, volume-mount-hack (init), increase-the-vm-max-map-count (init)
-----BEGIN CERTIFICATE-----
MIIDgzCCAmugAwIBAgIUFsouxoFwv5WGmclX5WnWzJNkg/AwDQYJKoZIhvcNAQEL
BQAwUTELMAkGA1UEBhMCQ0ExETAPBgNVBAcMCE1vbnRyZWFsMR0wGwYDVQQKDBRC
YXlzdHJlYW1Db3Jwb3JhdGlvbjEQMA4GA1UEAwwHcm9vdC1jYTAeFw0yMjA3MDgx
MTM2NDBaFw0zMjA3MDUxMTM2NDBaMFExCzAJBgNVBAYTAkNBMREwDwYDVQQHDAhN
b250cmVhbDEdMBsGA1UECgwUQmF5c3RyZWFtQ29ycG9yYXRpb24xEDAOBgNVBAMM
B3Jvb3QtY2EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCdKNWyLccR
ibJxnc2PTk0FQKqExJeB/xc9/OFA5HK0rFN5te/ray9F13vuEyg7OPl0uPpdX65i
ZW0r2biz4VqPpMHb5sVgN/zTJv1YWcCWHUAoxZ9hcUKps0hx3+xRFG4uCPb/ifeL
KuN47J4duTsSxC5Snpu1ZXIIp78YfdbF6zGJSfN+wwMxOwtOsxkf6UgpFDn2RYEN
biDoIEAc0QSNVzd91t/Z2oCDBTKEXt1LTgL7M4VxTXGUlb09i0RYyGUVEy9Svpd7
Iev1RzjzIsoOhB/EGVRrFU0LNAhOG4kmctSZPBfnoY9IUToGHWrboyRoZOIEk9iC
NLaHri/y18jnAgMBAAGjUzBRMB0GA1UdDgQWBBRc7VHWMB6u1u6CKemMcxvApPHY
lTAfBgNVHSMEGDAWgBRc7VHWMB6u1u6CKemMcxvApPHYlTAPBgNVHRMBAf8EBTAD
AQH/MA0GCSqGSIb3DQEBCwUAA4IBAQBQjhPeM8G+HzadewSTEmlteUIHlNTgnFWh
IMbRcvud3zt1CUzmNbgfyEuLCYt6AhaJubSJA4XAdHAKJgy6/RyxdqI6uFvfiHZZ
7s8OqPtUvJ5JZQJwp1xkVirtE0uuZEH0z0dMfbcuiCMsOwFQbZVl5Z8xcrjH2gCU
Ki9uwmTobotoHHb5hzMQxOQB8Otvw8b6mcBAjRFsNjZW4qO+1JtzR/YJFoeUZmFE
DQgF+Y77EO9Ygm7ukb69MTZDJ21mgW3cDafziSQzdr/2Q8sO+525PqZuk+rXAdgU
PPHUGDuix+ukuuOjIKlb/e7lylKr1KCQPcrvTRERaYck+kzgNiQA
-----END CERTIFICATE-----
PS D:\OneDrive - Company Corporation\Wazuh\wazuh-kubernetes-4.3-stable> kubectl exec -it wazuh-manager-master-0 -n wazuh -- cat /usr/share/wazuh-indexer/config/certs/root-ca.pem
cat: /usr/share/wazuh-indexer/config/certs/root-ca.pem: No such file or directory
command terminated with exit code 1
PS D:\OneDrive - Company Corporation\Wazuh\wazuh-kubernetes-4.3-stable> kubectl exec -it wazuh-manager-master-0 -n wazuh -- cat /etc/ssl/root-ca.pem          -----BEGIN CERTIFICATE-----
MIIDgzCCAmugAwIBAgIUFsouxoFwv5WGmclX5WnWzJNkg/AwDQYJKoZIhvcNAQEL
BQAwUTELMAkGA1UEBhMCQ0ExETAPBgNVBAcMCE1vbnRyZWFsMR0wGwYDVQQKDBRC
YXlzdHJlYW1Db3Jwb3JhdGlvbjEQMA4GA1UEAwwHcm9vdC1jYTAeFw0yMjA3MDgx
MTM2NDBaFw0zMjA3MDUxMTM2NDBaMFExCzAJBgNVBAYTAkNBMREwDwYDVQQHDAhN
b250cmVhbDEdMBsGA1UECgwUQmF5c3RyZWFtQ29ycG9yYXRpb24xEDAOBgNVBAMM
B3Jvb3QtY2EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCdKNWyLccR
ibJxnc2PTk0FQKqExJeB/xc9/OFA5HK0rFN5te/ray9F13vuEyg7OPl0uPpdX65i
ZW0r2biz4VqPpMHb5sVgN/zTJv1YWcCWHUAoxZ9hcUKps0hx3+xRFG4uCPb/ifeL
KuN47J4duTsSxC5Snpu1ZXIIp78YfdbF6zGJSfN+wwMxOwtOsxkf6UgpFDn2RYEN
biDoIEAc0QSNVzd91t/Z2oCDBTKEXt1LTgL7M4VxTXGUlb09i0RYyGUVEy9Svpd7
Iev1RzjzIsoOhB/EGVRrFU0LNAhOG4kmctSZPBfnoY9IUToGHWrboyRoZOIEk9iC
NLaHri/y18jnAgMBAAGjUzBRMB0GA1UdDgQWBBRc7VHWMB6u1u6CKemMcxvApPHY
lTAfBgNVHSMEGDAWgBRc7VHWMB6u1u6CKemMcxvApPHYlTAPBgNVHRMBAf8EBTAD
AQH/MA0GCSqGSIb3DQEBCwUAA4IBAQBQjhPeM8G+HzadewSTEmlteUIHlNTgnFWh
IMbRcvud3zt1CUzmNbgfyEuLCYt6AhaJubSJA4XAdHAKJgy6/RyxdqI6uFvfiHZZ
7s8OqPtUvJ5JZQJwp1xkVirtE0uuZEH0z0dMfbcuiCMsOwFQbZVl5Z8xcrjH2gCU
Ki9uwmTobotoHHb5hzMQxOQB8Otvw8b6mcBAjRFsNjZW4qO+1JtzR/YJFoeUZmFE
DQgF+Y77EO9Ygm7ukb69MTZDJ21mgW3cDafziSQzdr/2Q8sO+525PqZuk+rXAdgU
PPHUGDuix+ukuuOjIKlb/e7lylKr1KCQPcrvTRERaYck+kzgNiQA
-----END CERTIFICATE-----
PS D:\OneDrive - Company Corporation\Wazuh\wazuh-kubernetes-4.3-stable> kubectl exec -it wazuh-dashboard-5778695ccd-fq6r9 -n wazuh -- cat /usr/share/wazuh-dashboard/config/certs/root-ca.pem
-----BEGIN CERTIFICATE-----
MIIDgzCCAmugAwIBAgIUFsouxoFwv5WGmclX5WnWzJNkg/AwDQYJKoZIhvcNAQEL
BQAwUTELMAkGA1UEBhMCQ0ExETAPBgNVBAcMCE1vbnRyZWFsMR0wGwYDVQQKDBRC
YXlzdHJlYW1Db3Jwb3JhdGlvbjEQMA4GA1UEAwwHcm9vdC1jYTAeFw0yMjA3MDgx
MTM2NDBaFw0zMjA3MDUxMTM2NDBaMFExCzAJBgNVBAYTAkNBMREwDwYDVQQHDAhN
b250cmVhbDEdMBsGA1UECgwUQmF5c3RyZWFtQ29ycG9yYXRpb24xEDAOBgNVBAMM
B3Jvb3QtY2EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCdKNWyLccR
ibJxnc2PTk0FQKqExJeB/xc9/OFA5HK0rFN5te/ray9F13vuEyg7OPl0uPpdX65i
ZW0r2biz4VqPpMHb5sVgN/zTJv1YWcCWHUAoxZ9hcUKps0hx3+xRFG4uCPb/ifeL
KuN47J4duTsSxC5Snpu1ZXIIp78YfdbF6zGJSfN+wwMxOwtOsxkf6UgpFDn2RYEN
biDoIEAc0QSNVzd91t/Z2oCDBTKEXt1LTgL7M4VxTXGUlb09i0RYyGUVEy9Svpd7
Iev1RzjzIsoOhB/EGVRrFU0LNAhOG4kmctSZPBfnoY9IUToGHWrboyRoZOIEk9iC
NLaHri/y18jnAgMBAAGjUzBRMB0GA1UdDgQWBBRc7VHWMB6u1u6CKemMcxvApPHY
lTAfBgNVHSMEGDAWgBRc7VHWMB6u1u6CKemMcxvApPHYlTAPBgNVHRMBAf8EBTAD
AQH/MA0GCSqGSIb3DQEBCwUAA4IBAQBQjhPeM8G+HzadewSTEmlteUIHlNTgnFWh
IMbRcvud3zt1CUzmNbgfyEuLCYt6AhaJubSJA4XAdHAKJgy6/RyxdqI6uFvfiHZZ
7s8OqPtUvJ5JZQJwp1xkVirtE0uuZEH0z0dMfbcuiCMsOwFQbZVl5Z8xcrjH2gCU
Ki9uwmTobotoHHb5hzMQxOQB8Otvw8b6mcBAjRFsNjZW4qO+1JtzR/YJFoeUZmFE
DQgF+Y77EO9Ygm7ukb69MTZDJ21mgW3cDafziSQzdr/2Q8sO+525PqZuk+rXAdgU
PPHUGDuix+ukuuOjIKlb/e7lylKr1KCQPcrvTRERaYck+kzgNiQA
-----END CERTIFICATE-----
PS D:\OneDrive - Company Corporation\Wazuh\wazuh-kubernetes-4.3-stable>
```
