### ISSUE TITLE
Error when adding agent to multiple groups: "wazuh-remoted: ERROR: Cannot create multigroup directory 'var/multigroups/xxx': Permission denied"

### ISSUE THREAD

**Issue by phongvq** [wazuh/wazuh-kubernetes#283]
# Expected Behavior
When adding agent to mutiple group, `/var/ossec/var/multigroups/xxx` should be created in master, worker pvc.
# Current Behavior
Facing error: Cannot create multigroup directory '/var/ossec/var/multigroups/xxx': Permission denied"
# Possible Solution
This issue can be fixed by applying ONE of these solutions:
- use init container to set proper permission, owner for `/var/ossec/var/multigroups` (easy)
- re-configure wazuh image to create said directory with proper permission
# Steps to Reproduce
Done following steps __via Wazuh dashboard__ (haven't tested with commandline)
- create group `test-multi-group`
- create agent `test`
- add `test` agent to `test-multi-group` group
- now `test` belongs to `default` and `test`
- master/worker will try to create directory `multi-group-id` in `multigroups` directory, and the permission issue occured in both master and woker pods (view pod logs)
# Context (Environment)
- wazuh image: `wazuh/wazuh-manager:4.3.5`
# Detailed Description
```
root@wazuh-manager-master-0:/# ls /var/ossec/var/ -la
total 48
drwxr-x--- 1 root wazuh 4096 Jul 13 16:59 .
drwxr-x--- 1 root wazuh 4096 Jul 13 16:59 ..
drwxrwx--- 1 root wazuh 4096 Jul 13 17:07 db
drwxrwx--- 2 root wazuh 4096 Jun 23 18:05 download
drwxr-xr-x 3 root root  4096 Jul 13 17:07 multigroups
drwxrwx--- 1 root wazuh 4096 Jul 13 17:28 run
drwxrwx--- 2 root wazuh 4096 Jun 29 10:24 selinux
drwxrwx--- 2 root wazuh 4096 Jun 23 18:05 upgrade
drwxrwx--- 2 root wazuh 4096 Jun 23 18:05 wodles
```
`multigroups` has `root:root` owner and has different permission bits
# Possible Implementation
[WIP] will submit PR to fix this issue

**Comment by phongvq** [comment]
Hi @vcerenu  thank you for the information, I will close this issue.

**Comment by xBounceIT** [comment]
I have a Wazuh cluster using the multi node version and in 4.5.3 im still facing this issue. I also tried to delete the volumes and make it recreate them but no luck.

What am i missing?

**Comment by pthoelken** [comment]
Same here, seems to be, that the bug is already existing?

**Comment by celevra** [comment]
same here, is there a workaround?

**Comment by moivica** [comment]
This is still active 
wazuh 4.6.0

**Comment by ToXinE** [comment]
it is still an issue in 4.9.0

**Comment by Trapulo** [comment]
still in 4.10 running on docker

**Comment by phxyz12** [comment]
Ran into this issue on Wazuh single_node docker install using version 4.11.1. Affected folders with wrong permissions in the container:

```
/var/ossec/var/multigroups/
/var/ossec/integrations
/var/ossec/agentless/
```

I followed the standard procedure from the docs using the standart Docker compose file on a Ubuntu 24.04 server with Do
Docker.

Fixed using:

```bash
docker exec -it single-node-wazuh.manager-1 bash
    
chown wazuh /var/ossec/var/multigroups
chown wazuh /var/ossec/integrations
chown wazuh /var/ossec/agentless
```
