### ISSUE TITLE
Kubernetes 1.25.3 Rook-Ceph

### ISSUE THREAD

**Issue by cheslz** [wazuh/wazuh-kubernetes#340]
Kubernetes Version: 1.25.3 & 1.22.3
Environment: Bare-Metal K8s
Storage Provider: Rook-Ceph ( rook-ceph.rbd.csi.ceph.com )
We use rook-ceph as our storage back-end and am struggling to get the storage-class.yaml on the local-env/ to create and bind with rook-ceph. Is there any available resources I can use to solve this problem?
I understand the need for the new storage-class and would like to install this the correct way from the beginning.

`wazuh-storage               rook-ceph.rbd.csi.ceph.com      Delete          Immediate           false                  7m48s`

`NAME                                          STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS    AGE
wazuh-indexer-wazuh-indexer-0                 Pending                                      wazuh-storage   14s
wazuh-manager-master-wazuh-manager-master-0   Pending                                      wazuh-storage   14s
wazuh-manager-worker-wazuh-manager-worker-0   Pending                                      wazuh-storage   14s`

**Comment by gecube** [comment]
@cheslz Hi! Do you have some storage class that is already working in cluster? Brought by rook-ceph itself? If yes, could you type `kubectl get storageclass <its name> -oyaml` and put the output here? Thanks in advance

**Comment by gecube** [comment]
@cheslz good day! Is the issue still actual?
