### ISSUE TITLE
ERROR: SSL error (5). Connection refused by the manager. Maybe the port specified is incorrect

### ISSUE THREAD

**Issue by dashashutosh24** [wazuh/wazuh-kubernetes#381]
I am setting up wazuh cluster on kubernetes and the manager, workers and indexer are up and running with no issues. But while connecting agent to manager I am getting error: `wazuh-agentd: ERROR: SSL error (5). Connection refused by the manager. Maybe the port specified is incorrect`.  The manager cluster is running as pods in a k8s cluster on AWS and the auth, reporting and api services are exposed by nodeports which have a NLB pointing to it. I checked with nc -zv command and manager is reachable from the agent on ports 1514, 1515 and 55000. I have followed similar steps as : [https://wazuh.com/blog/deploying-wazuh-on-kubernetes-using-aws-eks/](url). I checked with `nc -zv <NLB_URL> 1515 1514 55000` command and manager is reachable from the agent on ports 1514, 1515 and 55000.

Nothing unusual is present in manager logs as well.
![Screenshot 2023-06-21 at 7 32 33 PM](https://github.com/wazuh/wazuh-kubernetes/assets/108323845/f8c6e727-f565-4069-86df-0cc935957930)

The auth config for the manager and worker is as follows:
<img width="739" alt="Screenshot 2023-06-21 at 7 49 30 PM" src="https://github.com/wazuh/wazuh-kubernetes/assets/108323845/3300b879-e0c1-4a55-b5b9-0d92367cb2aa">

Do I need to follow the steps mentioned in [https://documentation.wazuh.com/current/user-manual/agent-enrollment/security-options/agent-identity-verification.html](url) to create agent cert and key  and use it in agent config? Or can I skip the ssl step by enabling use_password option ?

**Comment by adiii717** [comment]
I'm experiencing the same problem. Have you managed to find a solution?

**Comment by k86td** [comment]
Same here. From what I've seen, it only did it with a Ubuntu 22.04 machine.

**Comment by k86td** [comment]
Turned out I was targeting port 1514 instead of 1515. I changed the config a bit, and was able to make it work. Maybe your issue was similar?

**Comment by c-bordon** [comment]
Hello Ashutosh, regarding the guide, in Step 4 of the guide you shared (https://wazuh.com/blog/deploying-wazuh-on-kubernetes-using-aws-eks/) port forwarding is explained that must be done to configure correctly. Keep in mind that ports 1515 and 1514 are not exposed outside the Kubernetes cluster, that is, you have to point your agents to the nodePort ports, example 30405.

With this command you will be able to see the ports that are configured to access from outside:

kubectl -n wazuh get services
