### ISSUE TITLE
AWS EFS:  Queue '/var/ossec/queue/ossec/queue' not accessible: 'Connection refused'

### ISSUE THREAD

**Issue by JPLachance** [wazuh/wazuh-kubernetes#45]
Hello!

I deployed a Wazuh Cluster in Kubernetes based on my own work and on https://github.com/wazuh/wazuh-kubernetes. To improve the master availability, I'm trying to use an EFS instead of an EBS.

I found an issue similar to this one (#23), but I was asked to open a new one.

My diff for my Kubernetes StatefulSet:
```
--- a/wazuh-master-sts.yaml
+++ b/wazuh-master-sts.yaml
@@ -30,6 +30,10 @@ spec:
         filebeat_conf_cm_version: '@(filebeat_conf_cm_version)'
     spec:
       volumes:
+        - name: wazuh-master-efs
+          nfs:
+            path: /
+            server: {{ undef "<computed>" .efs_dns_name }}
         - name: ossec-conf
           secret:
             secretName: wazuh-master-conf
@@ -87,9 +91,9 @@ spec:
               mountPath: /etc/filebeat/filebeat.yml
               subPath: filebeat.yml
               readOnly: true
-            - name: data
+            - name: wazuh-master-efs
               mountPath: /var/ossec/data
-            - name: data
+            - name: wazuh-master-efs
               mountPath: /etc/postfix
           ports:
             - containerPort: 1515
@@ -98,14 +102,3 @@ spec:
               name: cluster
             - containerPort: {{ .api_port }}
               name: api
-  volumeClaimTemplates:
-    - metadata:
-        name: data
-        namespace: '@(namespace)'
-      spec:
-        accessModes:
-          - ReadWriteOnce
-        storageClassName: gp2-encrypted-retained
-        resources:
-          requests:
-            storage: 50Gi
```

On boot of the Wazuh manager container, I get:
```
2019/05/29 01:45:17 wazuh-modulesd: ERROR: (1210): Queue '/var/ossec/queue/ossec/queue' not accessible: 'Connection refused'.
2019/05/29 01:45:18 ossec-remoted: ERROR: (1210): Queue '/queue/ossec/queue' not accessible: 'Connection refused'.
2019/05/29 01:45:18 ossec-analysisd: INFO: Reading rules file: 'ruleset/rules/0190-ms_ftpd_rules.xml'
2019/05/29 01:45:18 ossec-remoted: CRITICAL: (1211): Unable to access queue: '/queue/ossec/queue'. Giving up..
```

I tried to fix it by changing the [wazuh.runit.service](https://github.com/wazuh/wazuh-docker/blob/master/wazuh/config/wazuh.runit.service) script:
```SHELL
#!/bin/sh

/var/ossec/bin/ossec-control start
/var/ossec/bin/ossec-control start

tail -f /var/ossec/logs/ossec.log
```

It almost fixes the issue, but I still get some random failures (sometimes, some daemons fail to boot).

In Slack, @SitoRBJ said: "rootcheck is not finding the analysisd queue because that daemon is not yet standing".

How can we fix it? 😄 It looks like ossec-control is not aware of dependencies between each daemon it is managing. Therefore, if we give him a NFS with slow IO performances (compared to a SSD), it fails.

Thanks for your help!

**Comment by jm404** [comment]
Hi @JPLachance,

I'm complementing with some info for further investigation. This error is caused when de [Wazuh Daemons](https://documentation.wazuh.com/3.x/user-manual/reference/daemons/index.html) don't initialize in the proper order.

The desired order is:
```
ossec-authd 
wazuh-db 
ossec-execd 
ossec-analysisd 
ossec-syscheckd
ossec-remoted
ossec-logcollector 
ossec-monitord
wazuh-modulesd
wazuh-clusterd 
```

As @SitoRBJ stated, if `analysisd` takes extra time to initialize, rootcheck calls will fail, generating the error you faced. 

As far as I know you are using 3.6.1 right? I understand you are using this version for several reasons but let me strongly recommend upgrading Wazuh as in new versions most of this problems were fixed. 

Anyway, a possible solution would be initializing the daemons in the correct order, explicitly setting a sleep after `analysisd` in order to make sure it has time to start.

Did you manage to start them in the correct order?

From our side, we will investigate the reach of this problem in order to ensure it's not happening on newer versions.

**Comment by JPLachance** [comment]
Good morning,

At the moment, my solution is a readiness probe that automatically heals the Wazuh manager if it failed to boot all the services (by simply calling `service wazuh-manager start`). I pasted that script there: https://github.com/wazuh/wazuh-kubernetes/issues/52#issuecomment-519590274

My solution is a patch to a problem that, I think, should be handled by each Wazuh/Ossec services. If a service needs to boot after `analysisd`, that service should make sure `analysisd` is properly initialized. If it cannot boot because a dependency is not ready, it should notify the "orchestrator" (`ossec-control start`) and `ossec-control start` should know what to do.

I'll try to upgrade to Wazuh 3.9.5, but I first need to create a logs ingestion pipeline to move all my Wazuh alerts from a legacy Elasticsearch 6.3.1 cluster to a shiny new 6.8.1 cluster.

Until then, if you have a magic solution, I'll try it! 😄 

Thanks for the help!

**Comment by jm404** [comment]
Hi @JPLachance ,

No magical solutions from our side, I'm discussing with our team in case we can find an optimal solution for this.

Despite you solved the problem, I'm leaving the issue open in case we manage to find a fix or some user comes with a better approach.

Regards Lachance, glad to share thoughts with you!

Jose

**Comment by danielvalbuenasosa** [comment]
Hi, I just want to share my setup/experience using EFS with Wazuh Kubernetes:

The services are working OK at boot time:
root@wazuh-manager-master-0:/var/ossec/queue/ossec# service wazuh-manager status
wazuh-clusterd is running...
wazuh-modulesd is running...
ossec-monitord is running...
ossec-logcollector is running...
ossec-remoted is running...
ossec-syscheckd is running...
ossec-analysisd is running...
ossec-maild not running...
ossec-execd is running...
wazuh-db is running...
ossec-authd is running...
ossec-agentlessd not running...
ossec-integratord not running...
ossec-dbd not running...
ossec-csyslogd not running...

And relevant parts of server yaml file:
      volumes:
        - name: efs
          persistentVolumeClaim:
            claimName: efs
        - name: config
          configMap:
            name: wazuh-manager-master-conf

          volumeMounts:
            - name: efs
              mountPath: /var/ossec/data
            - name: config
              mountPath: /var/ossec/data/ossec.conf
              subPath: ossec.conf

It works without issues until now.

**Comment by jm404** [comment]
Hello @danielvalbuenasosa,

It's great to know it's working without issues for you. We've been doing some test on newer versions of Wazuh 3.9.x without being able to replicate this problem, this is related to old versions of Wazuh and I'ts relieving to know it's not appearing on new versions.

Thanks for your feedback, i'ts really appreciated

Best regards

Jose

**Comment by JPLachance** [comment]
Hello!

I went back to an EBS and the difference in performance is really huge. With Wazuh 3.6.1, an EFS really doesn't work well.

Still, if it works with the latest version of Wazuh, I guess we can close this issue. 🙂

Thanks for the help!

**Comment by jm404** [comment]
Hi @JPLachance, @danielvalbuenasosa,

Recently I've been able to reproduce the error described in the first post.

Logs error:
```
root@wazuh-manager-master-0:/# ps -aux | grep ossec
ossec      111  0.5  0.6 930948 47016 ?        Sl   14:23   0:00 /usr/bin/nodejs /var/ossec/api/app.js
root       301  0.0  0.0   7612   704 ?        S    14:23   0:00 tail -f /var/ossec/data/logs/api.log
root       365  0.0  0.0 121000  6160 ?        Sl   14:23   0:00 /var/ossec/bin/ossec-authd
ossec      377  0.0  0.0 186432  3056 ?        Sl   14:23   0:00 /var/ossec/bin/wazuh-db
root       454  0.0  0.0 292992  5188 ?        Sl   14:23   0:00 /var/ossec/bin/wazuh-modulesd
ossec      482  0.5  0.6 156380 53556 ?        S    14:23   0:00 /var/ossec/framework/python/bin/python3 


/var/ossec/framework/scripts/wazuh-clusterd.py
root       487  0.0  0.0   7612   776 ?        S    14:23   0:00 tail -f /var/ossec/data/logs/ossec.log
root       506  0.0  0.0  14516  1092 pts/0    S+   14:24   0:00 grep --color=auto ossec   
root@wazuh-manager-master-0:/# cat /var/ossec/logs/ossec.log | grep -vi info
2019/09/11 14:23:27 wazuh-modulesd: WARNING: The specific definition of the Red Hat feeds is deprecated. Use only redhat instead.
2019/09/11 14:23:28 ossec-syscheckd: WARNING: The check_unixaudit option is deprecated in favor of the SCA module.
2019/09/11 14:23:28 wazuh-modulesd: WARNING: The specific definition of the Red Hat feeds is deprecated. Use only redhat instead.
2019/09/11 14:23:43 ossec-syscheckd: ERROR: (1210): Queue '/var/ossec/queue/ossec/queue' not accessible: 'No such file or directory'.
2019/09/11 14:23:43 rootcheck: CRITICAL: (1211): Unable to access queue: '/var/ossec/queue/ossec/queue'. Giving up..
2019/09/11 14:23:43 ossec-remoted: ERROR: (1210): Queue '/queue/ossec/queue' not accessible: 'No such file or directory'.
2019/09/11 14:23:43 ossec-remoted: CRITICAL: (1211): Unable to access queue: '/queue/ossec/queue'. Giving up..
2019/09/11 14:23:43 wazuh-modulesd: ERROR: (1210): Queue '/var/ossec/queue/ossec/queue' not accessible: 'No such file or directory'.
2019/09/11 14:23:53 ossec-monitord: ERROR: (1210): Queue '/queue/ossec/queue' not accessible: 'No such file or directory'.
2019/09/11 14:23:53 ossec-monitord: CRITICAL: (1211): Unable to access queue: '/queue/ossec/queue'. Giving up..
2019/09/11 14:23:59 wazuh-modulesd: ERROR: (1210): Queue '/var/ossec/queue/ossec/queue' not accessible: 'No such file or directory'.
2019/09/11 14:24:15 wazuh-modulesd: ERROR: (1210): Queue '/var/ossec/queue/ossec/queue' not accessible: 'No such file or directory'.
2019/09/11 14:24:31 wazuh-modulesd: ERROR: (1210): Queue '/var/ossec/queue/ossec/queue' not accessible: 'No such file or directory'.
2019/09/11 14:24:31 wazuh-modulesd:syscollector: ERROR: Can't connect to queue.


root@wazuh-manager-master-0:/var/ossec/queue/ossec# ls -la
total 0
drwxrwx--- 1 ossec  ossec 81 Sep 11 14:23 .
drwxr-x--- 1 root   ossec 33 Aug 14 08:03 ..
srw-rw---- 1 root   ossec  0 Sep 11 14:23 auth
srw-rw---- 1 root   ossec  0 Sep 11 14:23 download
srw-rw---- 1 ossecr ossec  0 Sep 11 14:23 request
srw-rw---- 1 root   ossec  0 Sep 11 14:23 syscheck
srw-rw---- 1 root   ossec  0 Sep 11 14:23 wmodules
```

If restarting pod or Wazuh Manager the deamons are correctly started.

The problems looks like a race-condition which involves `syscheckd`, `analysisd` and `remoted`.

We are investigating possible solutions to this, will keep you updated

Best regards

Jose

**Comment by moshe0076** [comment]
@jm404 Hi,

Any progress with this issue?

We are running Wazuh on EKS with the data directory mounted into EFS (one master, two workers). 
 Any restart of the worker pods puts them in a situation that they are in a not READY state in kubernetes which require us to restart the master and worker pod a few times until the all the worker pods are back in READY state in Kubernetes. 

Thanks!

**Comment by jm404** [comment]
Hi @moshe0076,

Which version of Wazuh are you using? It's important for us in order to clarify if if the error still appear in newer versions.

Best regards,

Jose

**Comment by moshe0076** [comment]
We are using the Docker wazuh/wazuh:3.10.2_7.3.2

**Comment by jm404** [comment]
Noted. We will take this into consideration as we only saw the error appearing in previous versions until you reported it.
