### ISSUE TITLE
Application not found error

### ISSUE THREAD

**Issue by Aur0nd** [wazuh/wazuh-kubernetes#543]
Hey guys,

I've been trying to deploy to an on-prem k8s but I'm getting the below error (Note: I'm getting this error after I login with the credentials kibanaserver).

![Screenshot 2023-12-16 at 12 40 51](https://github.com/wazuh/wazuh-kubernetes/assets/71910902/730a81ad-22f7-4709-8fc6-29b51660a37e)

There's no warnings, no errors in the pods, no way I can troubleshoot this - any help would be really appreciated.

**Comment by julienkosinski** [comment]
I also have this problem, anything we could try to diagnose this?

Thank you very much!
