### ISSUE TITLE
Worker nodes not able to communicate with Wazuh manager master

### ISSUE THREAD

**Issue by shrivastavshubham34** [wazuh/wazuh-kubernetes#63]
Hello,
I'm trying to deploy the Wazuh server in Kubernetes (I'm using your Wazuh Kubernetes repo for reference).
I've deployed **wazuh/wazuh:3.9.0_6.7.2** docker image in my k8s cluster hosted on AWS.
I have performed all the steps as instructed.

The problem I am facing is:
The wazuh agent I registered shows as **never connected** in Kibana dashboard.

On further investigation, I tried to curl to my wazuh load balancer services at ports 1515 and 1514 from the machine which holds wazuh agent and it was able to connect to both of them with empty reply from load-balancer:1514/tcp

However, my agent logs showed me this:
```log
2019/10/08 21:07:27 ossec-agentd: WARNING: Unable to reload hostname for 'my-nlb-url-pointing-at-1514'. Using previous address.
2019/10/08 21:07:27 ossec-agentd: INFO: Trying to connect to server (my-nlb-url-pointing-at-1514/172.23.5.32:1514/tcp).
2019/10/08 21:07:31 ossec-syscheckd: INFO: (6010): File integrity monitoring scan frequency: 43200 seconds
2019/10/08 21:07:31 ossec-syscheckd: INFO: (6008): File integrity monitoring scan started.
2019/10/08 21:07:49 ossec-agentd: WARNING: Unable to reload hostname for 'my-nlb-url-pointing-at-1514'. Using previous address.
2019/10/08 21:07:49 ossec-agentd: INFO: Trying to connect to server (my-nlb-url-pointing-at-1514:1514/tcp).
2019/10/08 21:08:10 ossec-agentd: WARNING: Unable to reload hostname for 'my-nlb-url-pointing-at-1514'. Using previous address.
2019/10/08 21:08:10 ossec-agentd: INFO: Trying to connect to server (my-nlb-url-pointing-at-1514/IP_ADDRESS:1514/tcp).
2019/10/08 21:08:31 ossec-agentd: WARNING: Unable to reload hostname for 'my-nlb-url-pointing-at-1514'. Using previous address.
2019/10/08 21:08:31 ossec-agentd: INFO: Trying to connect to server (my-nlb-url-pointing-at-1514/IP_ADDRESS:1514/tcp).
```
My agent config file snippet:
```html
  <client>
    <server>
      <address>my-nlb-url-pointing-at-1514</address>
      <port>1514</port>
      <protocol>tcp</protocol>
    </server>
    <config-profile>centos, centos7, centos7.6</config-profile>
    <notify_time>10</notify_time>
    <time-reconnect>60</time-reconnect>
    <auto_restart>yes</auto_restart>
    <crypto_method>aes</crypto_method>
  </client>
```

On further investigation, I tried to find any errors on my wazuh manager master side using **cat /var/ossec/logs/ossec.log**  and could not find any warnings.

But when i connected to wazuh worker pod, I saw this error
```log
2019/10/08 21:25:20 wazuh-clusterd: ERROR: [Worker] [Main] Could not connect to master: [Errno -2] Name or service not known. Trying again in 10 seconds.
2019/10/08 21:25:30 wazuh-clusterd: ERROR: [Worker] [Main] Could not connect to master: [Errno -2] Name or service not known. Trying again in 10 seconds.
2019/10/08 21:25:40 wazuh-clusterd: ERROR: [Worker] [Main] Could not connect to master: [Errno -2] Name or service not known. Trying again in 10 seconds.
2019/10/08 21:25:50 wazuh-clusterd: ERROR: [Worker] [Main] Could not connect to master: [Errno -2] Name or service not known. Trying again in 10 seconds.
2019/10/08 21:26:00 wazuh-clusterd: ERROR: [Worker] [Main] Could not connect to master: [Errno -2] Name or service not known. Trying again in 10 seconds.
2019/10/08 21:26:10 wazuh-clusterd: ERROR: [Worker] [Main] Could not connect to master: [Errno -2] Name or service not known. Trying again in 10 seconds.
2019/10/08 21:26:20 wazuh-clusterd: ERROR: [Worker] [Main] Could not connect to master: [Errno -2] Name or service not known. Trying again in 10 seconds.
2019/10/08 21:26:30 wazuh-clusterd: ERROR: [Worker] [Main] Could not connect to master: [Errno -2] Name or service not known. Trying again in 10 seconds.
2019/10/08 21:26:40 wazuh-clusterd: ERROR: [Worker] [Main] Could not connect to master: [Errno -2] Name or service not known. Trying again in 10 seconds.
2019/10/08 21:26:50 wazuh-clusterd: ERROR: [Worker] [Main] Could not connect to master: [Errno -2] Name or service not known. Trying again in 10 seconds.
```

Its still not able to connect to wazuh master

**Comment by shrivastavshubham34** [comment]
I'm looking at the  **/var/ossec/etc/ossec.conf** in my worker nodes and I see this:

```html
    <nodes>
        <node>wazuh-manager-master-0.wazuh-cluster.wazuh.svc.cluster.local</node>
    </nodes>
```

My guess is wording is divided into something like:
```html
    <nodes>
        <node>name-of-master-pod.service-name.service-name.svc.cluster.local</node>
    </nodes>
```

Is this accurate?

**Comment by JPLachance** [comment]
Hello!

Yes it is. That address comes from the [Kubernetes StatefulSet stable network identity](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id) feature. That is configured using the [`wazuh-cluster`](https://github.com/wazuh/wazuh-kubernetes/blob/master/wazuh_managers/wazuh-cluster-svc.yaml) headless service.

- Workers need to reach the Master on port 1516.
- Agents need to reach the Master on port 1515 (authd) or 55000 (API) for registration
- Agents need to reach Workers on port 1514 to report events.

That is why we have 2 load balancers in our setup.
- [wazuh-master-svc.yaml](https://github.com/wazuh/wazuh-kubernetes/blob/master/wazuh_managers/wazuh-master-svc.yaml) targets only the Master pod
- [wazuh-workers-svc.yaml](https://github.com/wazuh/wazuh-kubernetes/blob/master/wazuh_managers/wazuh-workers-svc.yaml) targets only Workers

In AWS, you should see 2 load balancer.

Also, do you have Calico in your cluster? If so, you might need two NetworkPolicy. One for the Master and another one for Workers 🙂 

I hope this helps!
JP

**Comment by shrivastavshubham34** [comment]
@JPLachance , thanks for the quick reply!
Yes, I have the two load balancers up and running.

- **Agents are able to reach Master on port 1515 (authd) or 55000 (API) for registration.**
I tried the simple registration service of an agent and got the below output on agent:
![image](https://user-images.githubusercontent.com/13406071/66442915-cbf91680-e9f1-11e9-860b-c5f3d7699027.png)
And below output on manager:
![image](https://user-images.githubusercontent.com/13406071/66442963-17132980-e9f2-11e9-929e-85d13850c095.png)

And **curl -s -u foo:bar -k -X GET https://elb:55000/agents** returns expected output:
![image](https://user-images.githubusercontent.com/13406071/66443101-9b65ac80-e9f2-11e9-8c4d-c8bb15be62a0.png)


- **Agents need to reach Workers on port 1514 to report events.**
I tried to curl to wazuh worker service at 1514 from my agent machine and it returned empty reply from the server.
![image](https://user-images.githubusercontent.com/13406071/66443062-71ac8580-e9f2-11e9-912f-577de264ed26.png)

- **Workers need to reach the Master on port 1516.**
I have no idea how I can test this!!

I'm not using calico in my cluster.

**Comment by shrivastavshubham34** [comment]
I was able to resolve this issue, using the stable network identity feature of statefulSets, I had created a different namespace that was the root problem causing the worker nodes not to communicate with the master.
Thank you guys for the support!
