### ISSUE TITLE
Wazuh agent can't connect to managers in public

### ISSUE THREAD

**Issue by bangnh1** [wazuh/wazuh-kubernetes#64]
I'm trying to use Wazuh in Kubernetes on AWS. I modified wazuh-workers-svc.yaml for using internet-facing Load Balancer.
But my agent can't connect to Wazuh managers endpoint.

wazuh-workers-svc.yaml 
```
apiVersion: v1
kind: Service
metadata:
  name: wazuh-workers
  namespace: wazuh
  labels:
    app: wazuh-manager
spec:
  selector:
    app: wazuh-manager
    node-type: worker
  ports:
    - name: agents-events
      port: 1514
      targetPort: 1514
      protocol: TCP
  type: LoadBalancer
```

If I use real ip address when register agent, logs that I received in Wazuh workers as below:
```
2019/10/22 01:46:33 ossec-remoted: WARNING: (1213): Message from '100.112.0.0' not allowed.
2019/10/22 01:46:38 ossec-remoted: WARNING: (1213): Message from '100.119.0.0' not allowed.
2019/10/22 01:46:44 ossec-remoted: WARNING: (1213): Message from '100.116.0.0' not allowed.
2019/10/22 01:46:51 ossec-remoted: WARNING: (1213): Message from '100.112.0.0' not allowed.
2019/10/22 01:47:02 ossec-remoted: WARNING: (1213): Message from '100.119.0.0' not allowed.
2019/10/22 01:47:09 ossec-remoted: WARNING: (1213): Message from '100.116.0.0' not allowed.
```
If I use "any" in ip address field when register agent:
```
2019/10/22 01:50:49 ossec-remoted: WARNING: (1408): Invalid ID 007 for the source ip: '100.116.0.0' (name 'unknown').
2019/10/22 01:50:56 ossec-remoted: WARNING: (1408): Invalid ID 007 for the source ip: '100.112.0.0' (name 'unknown').
2019/10/22 01:51:01 ossec-remoted: WARNING: (1408): Invalid ID 007 for the source ip: '100.119.0.0' (name 'unknown').
```

If I turn on proxy protocol in ELB:
```
apiVersion: v1
kind: Service
metadata:
  name: wazuh-workers
  namespace: wazuh
  labels:
    app: wazuh-manager
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
spec:
  selector:
    app: wazuh-manager
    node-type: worker
  ports:
    - name: agents-events
      port: 1514
      targetPort: 1514
      protocol: TCP
  type: LoadBalancer
```

Output log from Wazuh workers:
```
2019/10/22 01:53:01 ossec-remoted: WARNING: Too big message size from 100.119.0.0 [13].
2019/10/22 01:53:01 ossec-remoted: WARNING: Too big message size from 100.116.0.0 [13].
2019/10/22 01:53:01 ossec-remoted: WARNING: Too big message size from 100.116.0.0 [14].
2019/10/22 01:53:05 ossec-remoted: WARNING: Too big message size from 100.119.0.0 [13].
2019/10/22 01:53:09 ossec-remoted: WARNING: Too big message size from 100.119.0.0 [13].
2019/10/22 01:53:09 ossec-remoted: WARNING: Too big message size from 100.116.0.0 [13].
2019/10/22 01:53:09 ossec-remoted: WARNING: Too big message size from 100.116.0.0 [14].
2019/10/22 01:53:11 ossec-remoted: WARNING: Too big message size from 100.112.0.0 [13].
2019/10/22 01:53:11 ossec-remoted: WARNING: Too big message size from 100.116.0.0 [14].
2019/10/22 01:53:11 ossec-remoted: WARNING: Too big message size from 100.116.0.0 [13].
```

How an agent can connect to my Wazuh cluster via internet? You have my appreciated for any ideas.

**Comment by jm404** [comment]
Hi @bangnh1,

I will try to reproduce your issue with the configurations you provided.

Let me ask you for further information in order to be able to reproduce your case:

- Are you using the Wazuh Docker images from https://github.com/wazuh/wazuh-docker/?
- Did you follow the https://github.com/wazuh/wazuh-kubernetes/blob/master/instructions.md guide?
- Which Agent OS are you using?
- Are you using SSL to register your agents?

Thanks for your patience.

Best regards,

Jose

**Comment by bangnh1** [comment]
Hi @jm404 ,
Thank you for response to me,

> Are you using the Wazuh Docker images from https://github.com/wazuh/wazuh-docker/?
 Yes

> Did you follow the https://github.com/wazuh/wazuh-kubernetes/blob/master/instructions.md guide?
I have an external ELK cluster, so I only install Wazuh cluster, I ignored the steps related to Elasticsearch. I will integrate when I'm done with Wazuh cluster. 

> Which` Agent OS are you using?
Amazon Linux 2018.03

> Are you using SSL to register your agents?
I don't use SSL

Do you have any suggestions for me? Thank u so much !!!

**Comment by jm404** [comment]
Hi @bangnh1,

Sorry for the late response, did you finally integrated the Wazuh Cluster in your EKS cluster?

Let us know if you still facing the same problem.

Best regards,

Jose
