### ISSUE TITLE
health-check-configmap doesn't exist

### ISSUE THREAD

**Issue by rabidsloth** [wazuh/wazuh-kubernetes#69]
The wazuh-master-sts.yaml file references a configmap named `health-check-configmap`, but this configmap doesn't seem to be included in the repo. It causes the deployment to fail because it cannot mount the volume. 

https://github.com/wazuh/wazuh-kubernetes/blob/master/wazuh_managers/wazuh-master-sts.yaml#L36

**Comment by jm404** [comment]
Hi @rabidsloth,

Sorry for the inconveniences, we have already removed related blocks to the pod-health which caused the issue, make sure to pull the changes and try again.

Best regards,

Jose

**Comment by rabidsloth** [comment]
Looks good, thanks!
