### ISSUE TITLE
Test: Multiple replicas for Logstash

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh-kubernetes#7]
Increase the number of replicas for Logstash and test if everything works as expected.

Document how to increase the number of replicas manually.

**Comment by SitoRBJ** [comment]
Hello team, 

The first step is to increase the number of replicas in the deployment file:

https://github.com/wazuh/wazuh-kubernetes/blob/master/elastic_stack/logstash/logstash-deploy.yaml#L16

```
spec:
  replicas: 3
  selector:
```

```
ubuntu@k8s-control-server:~/test/wazuh-kubernetes/wazuh_managers$ kubectl get pods --namespace wazuh
NAME                              READY     STATUS    RESTARTS   AGE
wazuh-elasticsearch-0             1/1       Running   0          10m
wazuh-kibana-f4d9c7944-zvcxz      1/1       Running   0          4m
wazuh-logstash-777b7cd47b-tvvnf   1/1       Running   0          2m
wazuh-logstash-777b7cd47b-w6slz   1/1       Running   0          2m
wazuh-logstash-777b7cd47b-wqxtn   1/1       Running   0          2m
wazuh-nginx-748fb8494f-86bzz      1/1       Running   0          4m
```

After making all the deployment, through an ssh tunnel we access to Nginx and from there to Kibana where we see alerts of our cluster. It is working successfully.

Regards,

Alfonso Ruiz-Bravo
