### ISSUE TITLE
Deprecated options in wazuh configmaps

### ISSUE THREAD

**Issue by aroes** [wazuh/wazuh-kubernetes#72]
Running kubectl logs on the master wazuh pod shows deprecated options are in use:

`2020/01/23 15:46:25 ossec-syscheckd: WARNING: The check_unixaudit option is deprecated in favor of the SCA module.`
`2020/01/23 15:46:25 wazuh-modulesd: WARNING: This vulnerability-detector declaration is deprecated. Use <vulnerability-detector> instead.`
`2020/01/23 15:46:25 wazuh-modulesd: WARNING: 'disabled' option at module 'vulnerability-detector' is deprecated. Use 'enabled' instead.`
`2020/01/23 15:46:25 wazuh-modulesd: WARNING: 'feed' option at module 'vulnerability-detector' is deprecated. Use 'provider' instead.`

**Comment by jm404** [comment]
Hi @aroes,

These warnings appear in the default configuration of Wazuh, in order to remove them please check your `/var/ossec/etc/ossec.conf` and update required fields.

Sorry for the late response, please let us know if you need further help.

Best regards,

Jose

**Comment by aroes** [comment]
Thank you, I saw later that the default conf is the same in the main wazuh repo. Is it intentional that it is using deprecated values or should I raise an issue there?

**Comment by jm404** [comment]
Hi @aroes,

It's intentional in order to make sure users are aware of this. I'm closing this issue as I assume the doubt is resolved, please feel free to open a new one anytime you need it

Best regards,

Jose
