### ISSUE TITLE
Kibana "no spaces match search criteria"

### ISSUE THREAD

**Issue by aroes** [wazuh/wazuh-kubernetes#73]
Following the instructions.md, using the elasticsearch cluster folder, in an AWS cluster, the Kibana instance redirects the base URL of the ALB to "[xyz]/spaces/space_selector#?_g=()". Most of the time, this page shows no spaces, as seen in the attached image. Occasionally upon refreshing the "Default" space will show up, but behavior after clicking it is shaky, and seems to redirect to the space_selector page again some time after.

![Capture](https://user-images.githubusercontent.com/17066386/73006008-d1903600-3e01-11ea-8630-bf03c3ecef0f.PNG)

The following error, possibly unrelated, appears in the pod logs repeatedly:
`{"type":"log","@timestamp":"2020-01-23T16:55:46Z","tags":["error","task_manager"],"pid":25,"message":"Failed to poll for work: [script_exception] link error, with { script_stack={ 0=\"doc['task.retryAt'].value\" & 1=\"     ^---- HERE\" } & script=\"doc['task.retryAt'].value || doc['task.runAt'].value\" & lang=\"expression\" } :: {\"path\":\"/.kibana_task_manager/_update_by_query\",\"query\":{\"ignore_unavailable\":true,\"refresh\":true,\"max_docs\":10,\"conflicts\":\"proceed\"},\"body\":\"{\\\"query\\\":{\\\"bool\\\":{\\\"must\\\":[{\\\"term\\\":{\\\"type\\\":\\\"task\\\"}},{\\\"bool\\\":{\\\"must\\\":[{\\\"bool\\\":{\\\"should\\\":[{\\\"bool\\\":{\\\"must\\\":[{\\\"term\\\":{\\\"task.status\\\":\\\"idle\\\"}},{\\\"range\\\":{\\\"task.runAt\\\":{\\\"lte\\\":\\\"now\\\"}}}]}},{\\\"bool\\\":{\\\"must\\\":[{\\\"bool\\\":{\\\"should\\\":[{\\\"term\\\":{\\\"task.status\\\":\\\"running\\\"}},{\\\"term\\\":{\\\"task.status\\\":\\\"claiming\\\"}}]}},{\\\"range\\\":{\\\"task.retryAt\\\":{\\\"lte\\\":\\\"now\\\"}}}]}}]}},{\\\"bool\\\":{\\\"should\\\":[{\\\"exists\\\":{\\\"field\\\":\\\"task.interval\\\"}},{\\\"bool\\\":{\\\"must\\\":[{\\\"term\\\":{\\\"task.taskType\\\":\\\"vis_telemetry\\\"}},{\\\"range\\\":{\\\"task.attempts\\\":{\\\"lt\\\":3}}}]}},{\\\"bool\\\":{\\\"must\\\":[{\\\"term\\\":{\\\"task.taskType\\\":\\\"lens_telemetry\\\"}},{\\\"range\\\":{\\\"task.attempts\\\":{\\\"lt\\\":3}}}]}}]}}]}}]}},\\\"sort\\\":{\\\"_script\\\":{\\\"type\\\":\\\"number\\\",\\\"order\\\":\\\"asc\\\",\\\"script\\\":{\\\"lang\\\":\\\"expression\\\",\\\"source\\\":\\\"doc['task.retryAt'].value || doc['task.runAt'].value\\\"}}},\\\"seq_no_primary_term\\\":true,\\\"script\\\":{\\\"source\\\":\\\"ctx._source.task.ownerId=params.ownerId; ctx._source.task.status=params.status; ctx._source.task.retryAt=params.retryAt;\\\",\\\"lang\\\":\\\"painless\\\",\\\"params\\\":{\\\"ownerId\\\":\\\"56ac10ee-3238-4965-9cf1-5978f7aec544\\\",\\\"retryAt\\\":\\\"2020-01-23T16:56:16.241Z\\\",\\\"status\\\":\\\"claiming\\\"}}}\",\"statusCode\":400,\"response\":\"{\\\"error\\\":{\\\"root_cause\\\":[{\\\"type\\\":\\\"script_exception\\\",\\\"reason\\\":\\\"link error\\\",\\\"script_stack\\\":[\\\"doc['task.retryAt'].value\\\",\\\"     ^---- HERE\\\"],\\\"script\\\":\\\"doc['task.retryAt'].value || doc['task.runAt'].value\\\",\\\"lang\\\":\\\"expression\\\"}],\\\"type\\\":\\\"search_phase_execution_exception\\\",\\\"reason\\\":\\\"all shards failed\\\",\\\"phase\\\":\\\"query\\\",\\\"grouped\\\":true,\\\"failed_shards\\\":[{\\\"shard\\\":0,\\\"index\\\":\\\".kibana_task_manager\\\",\\\"node\\\":\\\"K8FORPE1TnqqHWOaN2YJRw\\\",\\\"reason\\\":{\\\"type\\\":\\\"script_exception\\\",\\\"reason\\\":\\\"link error\\\",\\\"script_stack\\\":[\\\"doc['task.retryAt'].value\\\",\\\"     ^---- HERE\\\"],\\\"script\\\":\\\"doc['task.retryAt'].value || doc['task.runAt'].value\\\",\\\"lang\\\":\\\"expression\\\",\\\"caused_by\\\":{\\\"type\\\":\\\"parse_exception\\\",\\\"reason\\\":\\\"Field [task.retryAt] does not exist in mappings\\\"}}}]},\\\"status\\\":400}\"}"}`

I made a modification to the CPU requests in the yaml files for wazuh-elasticsearch (500m->200m) and wazuh workers (2->800m), otherwise left everything as-is.

I would appreciate any insight you may have.
Many thanks.

**Comment by jm404** [comment]
Hi @aroes

It seems to be an error related to Elasticsearch, let me ask you for some details about your deployment:

- The `wazuh-kubernetes` branch version you used
- Elasticsearch log and output of: `_cat/health` and `_cat/indices?v`
- Output of `journalctl -u kibana` 

Also, you could try navigate to `<your_kibana_address>/app/wazuh` from a private session in your browser in order to discard any error related with temporal files.

Thanks for your patience,

Best regards

Jose

**Comment by aroes** [comment]
Hi, thanks for the fast response. Note that this morning, I tried to deploy using the elasticsearch single node folder and it worked fine. Was able to reproduce the issue again by using the cluster folder. In case this could be a resource issue, I'll point out that I'm using 2 m4.xlarge nodes in my AWS cluster.

\-I'm using the master branch, latest commit (4284df3).
\-Output of 2 HTTP APIs from kibana container

```
bash-4.2$ curl -X GET "http://elasticsearch:9200/_cat/health?v&pretty"
epoch      timestamp cluster        status node.total node.data shards pri relo init unassign pending_tasks max_task_wait_time active_shards_percent
1579859940 09:59:00  docker-cluster green           1         1      5   5    0    0        0             0                  -                100.0%
bash-4.2$ curl -X GET "http://elasticsearch:9200/_cat/indices?v"
health status index                uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   .kibana_task_manager FAUsJyCzQg20iyQ4Sbab4w   1   1          2            0        8kb            8kb
yellow open   .kibana              bwoiOnIgQuS7ucpBiExOow   1   1          2            0     21.3kb         21.3kb
```

\-No journal files found in kibana container.
```
bash-4.2$ journalctl -u kibana
No journal files were found.
-- No entries --
``` 

\-I've attached the full logs for all 6 elasticsearch pods

\-Loading `/app/wazuh` in a private session makes no difference, and redirects to `spaces/space_selector#?_g=()`





[data-elasticsearch-0.txt](https://github.com/wazuh/wazuh-kubernetes/files/4107933/data-elasticsearch-0.txt)
[data-elasticsearch-1.txt](https://github.com/wazuh/wazuh-kubernetes/files/4107934/data-elasticsearch-1.txt)
[data-elasticsearch-2.txt](https://github.com/wazuh/wazuh-kubernetes/files/4107937/data-elasticsearch-2.txt)
[wazuh-elasticsearch-0.txt](https://github.com/wazuh/wazuh-kubernetes/files/4107938/wazuh-elasticsearch-0.txt)
[wazuh-elasticsearch-1.txt](https://github.com/wazuh/wazuh-kubernetes/files/4107939/wazuh-elasticsearch-1.txt)
[wazuh-elasticsearch-2.txt](https://github.com/wazuh/wazuh-kubernetes/files/4107940/wazuh-elasticsearch-2.txt)

**Comment by jm404** [comment]
Hi @aroes,

Sorry for the late response, did you manage to fix the error or you still facing this issue? If you still experience errors related to this please let us know.

Best regards,

Jose

**Comment by aroes** [comment]
Hello, I did not find a solution so I worked around the issue by using the non-cluster elasticsearch config files.

**Comment by jm404** [comment]
Hi @aroes

Thanks for the quick response. I suspect it's due to the low hardware specs assigned to ES but anyway we will review it just to make sure

Best regards,

Jose

**Comment by ponchov** [comment]
Hi, I have the same issue and I want to know if you found any solution for this issue?.

**Comment by mcdoolz** [comment]
Hi there; I'm using the Docker version of Kibana alongside the Docker ES in a small local development environment.

I see this appear completely at random and my only recourse to date has been to regenerate a container using the original image.  The Kibana interface appears normally, I create an index of * again, all is tickety boo for an indeterminate amount of time before suddenly, boom, rinse repeat.

**Comment by victor-fialkin-deltatre** [comment]
Have the same issue in Docker randomly. Restarting Kibana container helps

**Comment by gaollard** [comment]
Restarting Kibana container helps
