### ISSUE TITLE
Auth `use_password` enabled in master but not in worker

### ISSUE THREAD

**Issue by RamosFe** [wazuh/wazuh-kubernetes#730]
One of the community users found that the option `use_password` is enabled in the [master.conf](https://github.com/wazuh/wazuh-kubernetes/blob/master/wazuh/wazuh_managers/wazuh_conf/master.conf) but it is disabled in the [worker.conf](https://github.com/wazuh/wazuh-kubernetes/blob/master/wazuh/wazuh_managers/wazuh_conf/worker.conf).

https://github.com/wazuh/wazuh-kubernetes/blob/eedc893da191899d4bdeca021db1d0d0b967db2d/wazuh/wazuh_managers/wazuh_conf/master.conf#L303
https://github.com/wazuh/wazuh-kubernetes/blob/eedc893da191899d4bdeca021db1d0d0b967db2d/wazuh/wazuh_managers/wazuh_conf/worker.conf#L303

The [documentation](https://documentation.wazuh.com/current/user-manual/agent/agent-enrollment/security-options/using-password-authentication.html) suggest the following:
> Note In the case where the deployment architecture is using a multi-node cluster, ensure that password authorization is enabled on each manager node. This prevents unauthorized agent enrollment through an unsecured manager node.

We should enable `use_password` in the `worker.conf` to prevent unauthorized agent enrollment trouugh an unsecured manager node.

**Comment by teddytpc1** [comment]
The PR will be created tomorrow.
