### ISSUE TITLE
Following Setup Instructions Results in Never-Connected Clients

### ISSUE THREAD

**Issue by cbluth** [wazuh/wazuh-kubernetes#76]
following the instructions, as seen here: https://github.com/wazuh/wazuh-kubernetes/blob/b1d99161d5254645b4a3b6eae72f9cff35ae8011/instructions.md

will result in clients that cannot connect, showing a "never-connected" status.

in order to allow them to connect, a modification must be made on each client, and the client needs to be restarted.
here is the fix incase someone needs it:

```bash
# apt remove --purge wazuh-agent -y # you might need this to clear old keys from a pre-existing install
curl -so /tmp/wazuh-agent.deb \
    'https://packages.wazuh.com/3.x/apt/pool/main/w/wazuh-agent/wazuh-agent_3.11.3-1_amd64.deb'
sudo WAZUH_MANAGER_IP='wazuh.example.org' dpkg -i /tmp/wazuh-agent.deb
sed -i \
    's#<protocol>udp</protocol>#<protocol>tcp</protocol>#' \
    /var/ossec/etc/ossec.conf
systemctl restart wazuh-agent.service
```
the fix here is to change the protocol from `udp` to `tcp`, because the kubernetes service does not result in an available udp connection if you follow the instructions.

**Comment by cbluth** [comment]
in case anyone is interested, the kubernetes deployment manifest yaml that i used can be found here:
https://gist.github.com/cbluth/f5c6b14005f2529de8352f610a9543a5#file-wazuh-central-deployment-yaml

**Comment by jm404** [comment]
Hi @cbluth,

The AWS LoadBalancer is configured to handle the connections on TCP ports aswell as some other configs are prepared for this. As you stated the Agent must be configured to report on TCP.

Thanks for reporting this, we will implement required changes and open a PR for this. In case you have these changes already developed please feel free to open a PR and contribute to the project, we'll be glad to review it.

Best regards,

Jose

**Comment by cbluth** [comment]
@jm404 

> The AWS LoadBalancer is configured to handle the connections on TCP ports aswell as some other configs are prepared for this. As you stated the Agent must be configured to report on TCP.

you can see from my posted gist-file, that i have omitted the loadbalancers because i do not use AWS, and i have opted for routed `ClusterIP`s.
you can also see from the same gist-file that i have attempted to allow the k8s services (`kind: Service`) to listen on UDP also, so that the remote clients do not need to be reconfigured/restarted, but the actual pods themselves (`kind: StatefulSet` maybe masters or workers, or both?) are only listening on TCP, not on UDP.

>In case you have these changes already developed please feel free to open a PR and contribute to the project, we'll be glad to review it.

i would like to submit a PR for this, but the project is huge, and i dont know where to start, i am looking through the `ossec.conf` and i am new to this.

i see in the master-node `ossec.conf` there is this snippet:
```
      <remote>
        <connection>secure</connection>
        <port>1514</port>
        <protocol>tcp</protocol>
        <queue_size>131072</queue_size>
      </remote>
```

to allow it to listen on TCP **AND** UDP, can i do this??
---
```
      <remote>
        <connection>secure</connection>
        <port>1514</port>
        <protocol>tcp</protocol>
        <queue_size>131072</queue_size>
      </remote>
      <remote>
        <connection>secure</connection>
        <port>1514</port>
        <protocol>udp</protocol>
        <queue_size>131072</queue_size>
      </remote>
```

**Comment by cbluth** [comment]
i tried adding this to all three `ossec.conf` files:
```
      <remote>
        <connection>secure</connection>
        <port>1514</port>
        <protocol>tcp</protocol>
        <queue_size>131072</queue_size>
      </remote>
      <remote>
        <connection>secure</connection>
        <port>1514</port>
        <protocol>udp</protocol>
        <queue_size>131072</queue_size>
      </remote>
```
recreating the whole setup from scratch with the additional config above causes a failure like so: https://i.imgur.com/aZd6hkn.png
(api not responding)

removing the config snippet and recreating it again will result in a functional api

**Comment by jm404** [comment]
Hi @cbluth,

This might be related to https://github.com/wazuh/wazuh-kubernetes/issues/64, please let us know if you managed to fix the problem or need further help.

Best regards,

Jose

**Comment by jm404** [comment]
Hi @cbluth, I'm closing this issue as it's a duplicated of #64 as commented earlier, please feel free to share your thoughts on it on the referenced issue

Best regards,

Jose
