### ISSUE TITLE
Restarting (deleting) the master pod results in lost registration dates

### ISSUE THREAD

**Issue by cbluth** [wazuh/wazuh-kubernetes#77]
deleting the master pod creates an issue where the registration timestamps are lost.

![image](https://user-images.githubusercontent.com/6709636/75523674-be7a1280-5a0c-11ea-8c47-b0b93d655465.png)

**Comment by JPLachance** [comment]
I confirm I observe the same issue with Wazuh 3.10.2.

**Comment by manuasir** [comment]
Hello @cbluth and @JPLachance ,

This behavior can be reproduced when the `/var/ossec/queue/agents-timestamp` file is removed between manager restarts. Can you please check that file in your pod? It should look similar to this:

![image](https://user-images.githubusercontent.com/10210567/75698105-5ea29680-5cae-11ea-9b31-455106f106e4.png)

 Let me try to investigate this problem, it seems to only appear eventually so maybe it's something related to a weird road race when working with symlinks.

Cheers

**Comment by cbluth** [comment]
@manuasir thanks for the explanation
here is what i see in my master node:
```
root@wazuh-manager-master-0:~# file /var/ossec/queue/agents-timestamp
/var/ossec/queue/agents-timestamp: symbolic link to ../data/queue/agents-timestamp
root@wazuh-manager-master-0:~# cat /var/ossec/queue/agents-timestamp
root@wazuh-manager-master-0:~# ls -lsha /var/ossec/queue/agents-timestamp
0 lrwxrwxrwx 1 root root 30 Jan 28 18:22 /var/ossec/queue/agents-timestamp -> ../data/queue/agents-timestamp
root@wazuh-manager-master-0:~# ls -lsha /var/ossec/queue/../data/queue/agents-timestamp
0 -rw-rw---- 1 root ossec 0 Jan 28 09:33 /var/ossec/queue/../data/queue/agents-timestamp
root@wazuh-manager-master-0:~# file /var/ossec/queue/../data/queue/agents-timestamp
/var/ossec/queue/../data/queue/agents-timestamp: empty
root@wazuh-manager-master-0:~# 
```

**Comment by jm404** [comment]
Hi @cbluth , it seems that as you and @manuasir reproduced, the error is related to the agents-timestamp not being properly saved in the volume. This issue will be addressed in our refactor of  `wazuh-docker` images.

Best regards,

Jose

**Comment by jm404** [comment]
I'm closing this issue as this will be addressed at https://github.com/wazuh/wazuh-docker/issues/320, please feel free to open a new one if you need it.

Best regards,

Jose
