### ISSUE TITLE
Update Docker Image Version in Repository to Latest Available

### ISSUE THREAD

**Issue by imusabkhan** [wazuh/wazuh-kubernetes#776]
I am currently attempting to install Wazuh using the latest **wazuh-kubernetes repository 4.8.1**. During the installation process, I encountered an issue with the Docker image version specified in the repository. The repository references **Docker image version "5.0.0"**, but this version is not available on Docker Hub.

**File:** wazuh-kubernetes/wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
**Container Image:** wazuh/wazuh-dashboard:5.0.0
**Line:** 35

**File:** wazuh-kubernetes/wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
**Container Image:** wazuh/wazuh-indexer:5.0.0
**Line:** 62

**File:** wazuh-kubernetes/wazuh/wazuh_managers/wazuh-master-sts.yaml
**Container Image:** wazuh/wazuh-manager:5.0.0
**Line:** 44

**File:** wazuh-kubernetes/wazuh/wazuh_managers/wazuh-worker-sts.yaml
**Container Image:** wazuh/wazuh-manager:5.0.0
**Line:** 47

**Expected Behavior:**
The repository should reference a Docker image version that is available on Docker Hub.

**Actual Behavior:**
The repository references Docker image version "5.0.0", which is not available on Docker Hub.

**Reference:**
[Wazuh-Indexer](https://hub.docker.com/r/wazuh/wazuh-indexer/tags)
[Wazuh-Dashboard](https://hub.docker.com/r/wazuh/wazuh-dashboard/tags)
[Wazuh-Manager](https://hub.docker.com/r/wazuh/wazuh-manager/tags)

<img width="834" alt="1- Wazuh-Manager-2" src="https://github.com/user-attachments/assets/4f08beba-6005-405b-8716-f1accef90d90">

<img width="1435" alt="2- Docker-images" src="https://github.com/user-attachments/assets/67ca0018-f160-424a-96f5-bb938c67dd9c">

<img width="875" alt="1- Wazuh-Dashboard" src="https://github.com/user-attachments/assets/deacbcf5-ea44-4365-a036-2a956625e02b">

<img width="887" alt="1- Wazuh-Indexer-1" src="https://github.com/user-attachments/assets/7df51de7-a822-4fb2-b65e-2028749a2c34">

<img width="1420" alt="3- DockerHub-1" src="https://github.com/user-attachments/assets/72c7030d-fd00-4fcc-b2c8-3fa730464554">

<img width="1436" alt="3- DockerHub-3" src="https://github.com/user-attachments/assets/6b1022c4-453c-486f-b70f-0cbeaaef524e">

<img width="1439" alt="3- DockerHub-2" src="https://github.com/user-attachments/assets/bd375038-9318-4743-bf83-c3e18cef06a1">

**Comment by crlsgms** [comment]
If you had pulled the repo from the instructions, it will fetch the generic / master branch which the tags are with 5.0.0 that are not available yet, suggestion is to get on the release link and get the zip from there - [v4.8.1](https://github.com/wazuh/wazuh-kubernetes/archive/refs/tags/v4.8.1.zip)

another way to have more control, or if you use a local registry is to add on your overlays kustomization.yml file all used images and tailor to your desired version, for example on mine using harbor registry:

`images:
  - name: wazuh/wazuh-dashboard:4.8.0
    newName: harbor.local:30003/wazuh-proxy/wazuh/wazuh-dashboard
    newTag: 4.8.0
  - name: wazuh/wazuh-indexer:4.8.0
    newName: harbor.local:30003/wazuh-proxy/wazuh/wazuh-indexer
    newTag: 4.8.0
  - name: wazuh/wazuh-manager:4.8.0
    newName: harbor.local:30003/wazuh-proxy/wazuh/wazuh-manager
    newTag: 4.8.0
  - name: busybox
    newName: harbor.local:30003/wazuh-proxy/busybox
    newTag: latest
  - name: alpine
    newName: harbor.local:30003/wazuh-proxy/alpine
    newTag: latest`

**Comment by davidcr01** [comment]
Hello. 

The issue you encountered is related to our versioning and release system. In our repositories, the `master` or the `main` branch contains the latest development code (n this case, the 5.0.0 version). This version is currently being developed so the Docker images are not built.

If you want to deploy the latest Wazuh version, I suggest you to check out the "Releases" part of the [repository](https://github.com/wazuh/wazuh-kubernetes/releases):
![image](https://github.com/user-attachments/assets/414f6243-ad58-491e-87d4-e7a627a8ae13). 

There, you can check which is the latest version. This is also documented in our [official documentation](https://documentation.wazuh.com/current/release-notes/index.html).

Then, once you get the latest version of Wazuh (or the version you want to deploy), change the branch of your local repository (assuming that the repository is cloned in your machine) with the `git checkout` command. For example, if you want to deploy the Wazuh v4.8.2 version, use the `git checkout v4.8.2` command and you will move to the `v4.8.2` tag, deploying the correct version.

Hope it helps. Regards.
