### ISSUE TITLE
support kustomize

### ISSUE THREAD

**Issue by rverma-jm** [wazuh/wazuh-kubernetes#88]
Can you please add a Kustomization file to support remote install.

**Comment by jm404** [comment]
Hi @rverma-jm, sorry but I think I don't fully understand your request, could you provide more information about how implementing Kustomization would be useful for the repo? Some examples would be great

Best regards,

Jose

**Comment by manuasir** [comment]
Hello @rverma-jm ,

We have this approach in a [development branch](https://github.com/wazuh/wazuh-kubernetes/blob/local-environment/minikube/kustomization.yaml)
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds wazuh namespace to all resources.
namespace: wazuh

# resources to apply
resources:
- base.yaml
- elastic/elasticsearch-svc.yaml
- elastic/elasticsearch-sts.yaml
- kibana/kibana-svc.yaml
- kibana/kibana-deploy.yaml
- kibana/nginx-svc.yaml
- kibana/nginx-deploy.yaml
- wazuh/wazuh-svc.yaml
- wazuh/wazuh-conf.yaml
- wazuh/wazuh-sts.yaml
```

You would just to adjust the paths to your needs and then apply it like this
```
kubectl apply -k .
```

I hope that helps.

Regards
